eclipse-edc/IdentityHub

extensions/identity-hub-verifier/build.gradle.kts
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtension.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtensionTest.java

Publish IdentityHub Credentials Verifier to Maven, so that it can be used in MVD EDC.
Also removed unused setting (which we forgot to remove in a previous PR).
https://github.com/agera-edc/IdentityHub/issues/21

Credentials Verifier Maven artifact

---

spi/identity-hub-spi/src/main/java/org/eclipse/dataspaceconnector/identityhub/credentials/VerifiableCredentialsJwtServiceImpl.java
spi/identity-hub-spi/src/test/java/org/eclipse/dataspaceconnector/identityhub/credentials/VerifiableCredentialsJwtServiceTest.java

Add issue time claim to VC JWT payload.
This allows writing system tests in registration service that can wait for VCs to be pushed to Identity Hub. With an issue time, tests can run multiple times and ensure a new VC was generated (vs. a VC from a previous test run).
https://github.com/agera-edc/MinimumViableDataspace/issues/13

Add issue time JWT claim

---

.github/actions/gradle-setup/action.yml
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtensionTest.java
gradle.properties

Uses the latest EDC M5 version in local and CI builds. Removes the local checkout entirely.
ALso fixes a broken test.

chore: use EDC M5 version

---

client-cli/src/main/java/org/eclipse/dataspaceconnector/identityhub/cli/IdentityHubCli.java
client-cli/src/main/java/org/eclipse/dataspaceconnector/identityhub/cli/ListVerifiableCredentialsCommand.java
client-cli/src/test/java/org/eclipse/dataspaceconnector/identityhub/cli/CliTestUtils.java
client-cli/src/test/java/org/eclipse/dataspaceconnector/identityhub/cli/VerifiableCredentialsCommandTest.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtension.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/DidJwtCredentialsVerifier.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/IdentityHubCredentialsVerifier.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtensionTest.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/IdentityHubCredentialsVerifierTest.java
spi/identity-hub-spi/build.gradle.kts
spi/identity-hub-spi/src/main/java/org/eclipse/dataspaceconnector/identityhub/credentials/VerifiableCredentialsJwtServiceImpl.java
spi/identity-hub-spi/src/test/java/org/eclipse/dataspaceconnector/identityhub/credentials/VerifiableCredentialsJwtServiceTest.java

Introduce a fix for the "NoSuchMethodError" observed in the CI pipeline for the cloud system tests: https://github.com/agera-edc/MinimumViableDataspace/runs/7693917471?check_suite_focus=true
The cause of the issue is still unclear. It seems that the `toJSONObject` method is not available due to a version mismatch of the nimbus library. This does not happen when running tests locally, nor when running the local system tests in CI. Why this only manifests when running the cloud system tests in CI is still a mystery.
This PR introduces a workaround by adapting the `VerifiableCredentialsJwtServiceImpl` not to use this method.
Logging was improved in order to debug the issue and this PR contains additional logging statements that proved to be useful.
Fix Identity Hub integration in MVD. …

Identity Hub: Fix VerifiableCredentialsJwtServiceImpl's "NotSuchMethodError" (#43)

---

extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/DidJwtCredentialsVerifierTest.java
identity-hub-core/identity-hub-client/build.gradle.kts
identity-hub-core/identity-hub-client/src/test/java/org/eclipse/dataspaceconnector/identityhub/client/IdentityHubClientImplIntegrationTest.java
identity-hub-core/identity-hub-client/src/test/java/org/eclipse/dataspaceconnector/identityhub/client/IdentityHubClientImplTest.java

In tests we use ConsoleMonitor and Monitor mock.
The PR make it consistent by using Monitor mock in every tests.
For consistency and have a clean test output console.
No issue, it is just a quick cleanup for consistency.

Use Monitor mock in tests instead of ConsoleMonitor.

---

docs/developer/decision-records/2022-07-01-get-claims/README.md
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/IdentityHubCredentialsVerifier.java

Document the content of the Map<String, Object> returned by the IdentityHubCredentialsVerifier.

Document the format of the credentials returned by the IdentityHubCredentialsVerifier

---

extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/AggregatedResult.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/DidJwtCredentialsVerifier.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/IdentityHubCredentialsVerifier.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/JwtCredentialsVerifier.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/DidJwtCredentialsVerifierTest.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/IdentityHubCredentialsVerifierTest.java

IdentityHubCredentialsVerifier fails if the signature verification of at least one VerifiableCredential fail.
We decided to always fail if something goes wrong with verifiable credentials, to notice potential problems easily.
In MVD, the VerfiableCredentials should always be valid.
Next steps: Adapt registry service to the new contract of the JwtCredentialsVerifier.
Added a test to increase the DidJwtCredentialsVerifier test coverage to 100%
Added a VerificationResult class to contain result + errors.
The long term goal is that the IdentityHubCredentialsVerifier returns an object that contains the successful result + failures, to let the client decide how to proceed with errors.
https://github.com/agera-edc/IdentityHub/issues/47

IdentityHubCredentialsVerifier: Fails if one VC signature verification fails

---

.github/workflows/verify.yaml
build.gradle.kts

Upload IdentityHub test coverage to codecov.
Report can be seen here: https://codecov.io/gh/agera-edc/IdentityHub/tree/feature%2F250%2F250-codecov
To have codecov report to see the test coverage in PRs.
https://github.com/agera-edc/MinimumViableDataspace/issues/250

Upload test coverage to codecov.

---

client-cli/src/main/java/org/eclipse/dataspaceconnector/identityhub/cli/GetSelfDescriptionCommand.java
client-cli/src/main/java/org/eclipse/dataspaceconnector/identityhub/cli/IdentityHubCli.java
client-cli/src/main/java/org/eclipse/dataspaceconnector/identityhub/cli/SelfDescriptionCommand.java
client-cli/src/test/java/org/eclipse/dataspaceconnector/identityhub/cli/VerifiableCredentialsCommandTest.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtension.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/JwtCredentialsVerifierExtension.java
extensions/identity-hub-verifier/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtensionTest.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/DidJwtCredentialsVerifierTest.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/IdentityHubCredentialsVerifierTest.java
extensions/identity-hub/build.gradle.kts
extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/identityhub/IdentityHubExtension.java
extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/identityhub/api/IdentityHubController.java
extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/identityhub/selfdescription/SelfDescriptionLoader.java
extensions/identity-hub/src/main/resources/default-self-description.json
extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/api/IdentityHubControllerTest.java
extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/selfdescription/SelfDescriptionLoaderTest.java
extensions/identity-hub/src/test/resources/invalid-self-description.txt
extensions/identity-hub/src/test/resources/self-description.json
gradle.properties
identity-hub-core/identity-hub-client/src/main/java/org/eclipse/dataspaceconnector/identityhub/client/IdentityHubClient.java
identity-hub-core/identity-hub-client/src/main/java/org/eclipse/dataspaceconnector/identityhub/client/IdentityHubClientImpl.java
identity-hub-core/identity-hub-client/src/test/java/org/eclipse/dataspaceconnector/identityhub/client/IdentityHubClientImplIntegrationTest.java
identity-hub-core/identity-hub-client/src/test/java/org/eclipse/dataspaceconnector/identityhub/client/IdentityHubClientImplTest.java
resources/openapi/yaml/identity-hub.yaml
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/identityhub/systemtests/VerifiableCredentialsIntegrationTest.java

Adds an endpoint serving Self-Description. It also introduces the associated command in the CLI client for getting the Self-Description in the console. 
Note that the current code enables to provide a Self-Description using the setting `edc.self.description.document.path`. If this setting is omitted, then a default self-description from the classpath is loaded.
See https://github.com/agera-edc/IdentityHub/issues/38.
Closes https://github.com/agera-edc/IdentityHub/issues/11

Add Self-Description endpoint (#37)

---

client-cli/build.gradle.kts
client-cli/src/test/java/org/eclipse/dataspaceconnector/identityhub/cli/CliTestUtils.java
client-cli/src/test/java/org/eclipse/dataspaceconnector/identityhub/cli/VerifiableCredentialsCommandTest.java
extensions/identity-hub-verifier/build.gradle.kts
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtensionTest.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/DidJwtCredentialsVerifierTest.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/IdentityHubCredentialsVerifierTest.java
extensions/identity-hub/build.gradle.kts
extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/api/IdentityHubControllerTest.java
extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/processor/CollectionsWriteProcessorTest.java
extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/store/IdentityHubInMemoryStoreTest.java
gradle.properties
identity-hub-core/identity-hub-client/build.gradle.kts
identity-hub-core/identity-hub-client/src/test/java/org/eclipse/dataspaceconnector/identityhub/client/IdentityHubClientImplIntegrationTest.java
identity-hub-core/identity-hub-client/src/test/java/org/eclipse/dataspaceconnector/identityhub/client/IdentityHubClientImplTest.java
spi/identity-hub-spi/build.gradle.kts
spi/identity-hub-spi/src/test/java/org/eclipse/dataspaceconnector/identityhub/credentials/VerifiableCredentialsJwtServiceTest.java
spi/identity-hub-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/identityhub/junit/testfixtures/VerifiableCredentialTestUtil.java
system-tests/launcher/build.gradle.kts
system-tests/tests/build.gradle.kts
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/identityhub/systemtests/VerifiableCredentialsIntegrationTest.java

completely removes the `javafaker` dependency from the project as it is not needed.
cleanup. small dependency footprint.
.

chore: remove java faker

---

client-cli/build.gradle.kts
client-cli/src/test/java/org/eclipse/dataspaceconnector/identityhub/cli/VerifiableCredentialsCommandTest.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/DidJwtCredentialsVerifier.java
extensions/identity-hub-verifier/src/test/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtensionTest.java
gradle.properties
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/identityhub/systemtests/VerifiableCredentialsIntegrationTest.java

Bumps versions of all dependencies, including EDC, which was bumped to `milestone-6`.
This is intended to pave the way for the first real release of IdentityHub to MavenCentral.

chore: bumped all versions

---

.github/workflows/release-identityhub.yml

Adds a workflow file to trigger the creation of a release on Jenkins using Github Actions.
Convenient way to create a new release/snapshot from withing Github
.
.

build: add release workflow file

---

.github/workflows/release-identityhub.yml

changes the name of the input parameter for the release workflow.

fix: fixed input param for release workflow

---

gradle.properties

Reverts the version of Nimbus JWT used by IdentityHub to 8.23.
EDC still uses 8.23, so referencing a different version in IH would potentially (and actually) cause runtime problems, i.e. `NoSuchMethodError`s.
Note that this does not occur in IH directly, but in _it's_ downstream projects, e.g. `RegistrationService`.

chore: revert nimbus version to 8.23 (used by EDC)

---

extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtension.java
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/JwtCredentialsVerifierExtension.java
extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/identityhub/IdentityHubExtension.java
gradle.properties
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/identityhub/systemtests/VerifiableCredentialsIntegrationTest.java

The recent introduction of the `runtime-metamodel` library requires a few changes in IdentityHub as well, specifically package declarations.
prepare for any upcoming EDC releases.
- from this point forward, `IdentityHub` will use EDC version `0.0.1-20220930-SNAPSHOT` version, which is the latest nightly at the time of this writing.

chore: adopt current EDC snapshot 

---

extensions/identity-hub/build.gradle.kts
extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/identityhub/IdentityHubExtension.java
extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/identityhub/processor/CollectionsQueryProcessor.java
extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/identityhub/processor/CollectionsWriteProcessor.java
extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/processor/CollectionsWriteProcessorTest.java

Adds transactional access to the `IdentityHubStore`
As of now the transactional context was not created.
Closes #44

fix(IdentityHub): adds transactional access to IdentityHubStore

---

.github/workflows/verify.yaml
extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/identityhub/processor/CollectionsWriteProcessor.java
resources/openapi/yaml/identity-hub.yaml
spi/identity-hub-store-spi/build.gradle.kts

It fixes a syntax error on the verify.yml workflow config
Fix the CI

fix(actions): resolves verify workflow file error

---

client-cli/README.md
core/identity-hub/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
gradle.properties

Changes the project group from `org.eclipse.edc.identityhub` to `org.eclipse.edc`

chore(groupId): rename project groupId to org.eclipse.edc

---

extensions/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/IdentityHubApiExtension.java

chore: removes last @EdcSetting

---

.github/workflows/verify.yaml
settings.gradle.kts

Use the SNAPSHOT version of EDC
to have the ability for cascaded builds and up-to-date versions, avoid feature gaps
- disabled a failing action for now, will re-enable before merging
.

chore: use SNAPSHOT version of EDC

---

core/identity-hub/src/main/java/org/eclipse/edc/identityhub/processor/CollectionsWriteProcessor.java

Adds a small code change to accomodate for changes done upstream due to the upgrade to Nimbus 9.
compatibility
- Nimbus 9 gets shipped with the latest SNAPSHOT of the VersionCatalog, which was merged in https://github.com/eclipse-edc/GradlePlugins/pull/62
Closes #https://github.com/eclipse-edc/Connector/issues/2302

chore: updated code to accomodate for latest nimbus

---

.github/workflows/verify.yaml
client-cli/build.gradle.kts
system-tests/build.gradle.kts

Wanted to bump bouncycastle version, but I found out that these dependencies are not necessary, so I got rid of them.
cleanup
Made the CI run on every push on every branch, as it is in the `Connector` repository

build(deps): remove unnecessary bouncycastle dependencies

---

extensions/store/sql/identity-hub-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStore.java
extensions/store/sql/identity-hub-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStoreExtension.java
extensions/store/sql/identity-hub-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/PostgresParticipantStoreTest.java

Apply AbstractSqlStore class and PostgresqlStoreSetupExtension in test.
Code simplification.

refactor(SqlIdentityHubStore): apply AbstractSqlStore class and PostgresqlStoreSetupExtension in test

---

extensions/identity-hub-verifier-jwt/build.gradle.kts

Fixes the name of the artifact for  module `identity-hub-verifier-jwt`

chore(build): fix verifier-jwt artifact name

---

.github/workflows/verify.yaml
extensions/store/cosmos/identity-hub-store-cosmos/build.gradle.kts
extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStore.java
extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStoreConfig.java
extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStoreExtension.java
extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/model/IdentityHubRecordDocument.java
extensions/store/cosmos/identity-hub-store-cosmos/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/store/cosmos/identity-hub-store-cosmos/src/test/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStoreIntegrationTest.java
extensions/store/cosmos/identity-hub-store-cosmos/src/test/java/org/eclipse/edc/identityhub/store/cosmos/model/IdentityHubRecordDocumentSerializationTest.java
extensions/store/sql/identity-hub-store-sql/build.gradle.kts
settings.gradle.kts

Provide CosmosDB implementation of the `IdentityHubStore` which is used for storing Verifiable Credentials.
Provide persistence for the `IdentityHubStore`.
Closes #39.

feat(IdentityHubStore): provide CosmosDB implementation of `IdentityHubStore`

---

.github/actions/bump-version/action.yml
.github/workflows/release-identityhub.yml

Adds a job to automatically bump the version after a GH release
updated the version automatically

build: add action to bump the snapshot version

---

.github/actions/bump-version/action.yml
gradle.properties
gradle/libs.versions.toml
identity-hub-cli/README.md

Update snapshot version to `0.1.0-SNAPSHOT`
Our next release version will be `0.1.0`, thus the next snapshot will be `0.1.1-SNAPSHOT` and the automatic version bump mechanism currently only bumps the `patch` version.
- depends on https://github.com/eclipse-edc/GradlePlugins/pull/162
- depends on https://github.com/eclipse-edc/Connector/pull/3108
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md)._

chore: update snapshot version to 0.1.0-SNAPSHOT

---

.github/workflows/verify.yaml
DEPENDENCIES
core/identity-hub-api/src/main/java/org/eclipse/edc/identityservice/api/validation/PresentationQueryValidator.java
core/identity-hub-core/build.gradle.kts
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryCredentialStore.java
core/identity-hub-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/defaults/InMemoryCredentialStoreTest.java
core/identity-hub-transform/src/main/java/org/eclipse/edc/identityhub/transform/JsonObjectToPresentationQueryTransformer.java
launcher/build.gradle.kts
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/CredentialStore.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/model/IdentityResource.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/model/VcState.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/model/VerifiableCredentialResource.java
spi/identity-hub-store-spi/src/test/java/org/eclipse/edc/identityhub/spi/store/model/VerifiableCredentialResourceTest.java

This PR adds a `CredentialStore` interface plus an In-Memory implementation for it, which is the default.
Subsequent work items (#153, #154) will depend on a storage backend for VerifiableCredentials.
- this store really is just a CRUD backend, more elaborate operations like composing a query "by type" have to be done in other layers.
- added some dummy/NOOP services, just so the launcher is able to start. those will get replaced with actual services in #153 and #154.
- fixed minor bugs in the validator and the transformer
- added the `identity-did-web` module to the launcher
Closes #163
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://g>

feat: add `CredentialStore` + inmem implementation

---

DEPENDENCIES
core/identity-hub-api/src/main/java/org/eclipse/edc/identityservice/api/v1/PresentationApiController.java
core/identity-hub-api/src/test/java/org/eclipse/edc/identityservice/api/v1/PresentationApiControllerTest.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CredentialQueryResolverImpl.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/defaults/EdcScopeToCriterionTransformer.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/CredentialQueryResolverImplTest.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/defaults/EdcScopeToCriterionTransformerTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ResolutionApiComponentTest.java
extensions/cryptography/public-key-provider/src/main/java/org/eclipse/edc/identityhub/publickey/resolver/PublicKeyWrapperExtension.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/ScopeToCriterionTransformer.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/resolution/CredentialQueryResolver.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/resolution/QueryFailure.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/resolution/QueryResult.java

This PR implements the `CredentialQueryResolver` that accepts a presentation query and returns a list of VerifiableCredentials.
It also adds a default Scope-to-Criterion converter.
Being able to query the database based off of a scope string.
- Using DIF Presentation Exchange definitions is not yet supported. Attempting to do that will throw an `UnsupportedOperationException`.
- the `EdcScopeToCriterionTransformer` is intended for demo purposes only, do **not** use it in production code!
Closes #153

feat: implement CredentialQueryResolver

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/PresentationGeneratorImpl.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/token/verification/AccessTokenVerifierImpl.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/PresentationGeneratorImplTest.java

This PR avoids the generation of nested empty arrays when generating VPs without any VC. 
- Before: `{"vpToken": [ [] ], ...}`
- After: `{"vpToken": [], ...}`
Bugfix

feat!: avoid empty nested arrays when generating VP

---

DEPENDENCIES
core/identity-hub-api/src/main/java/org/eclipse/edc/identityservice/api/v1/PresentationApiController.java
core/identity-hub-api/src/test/java/org/eclipse/edc/identityservice/api/v1/PresentationApiControllerTest.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CredentialQueryResolverImpl.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/PresentationCreatorRegistryImpl.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/PresentationGeneratorImpl.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationCreator.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/defaults/EdcScopeToCriterionTransformer.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryCredentialStore.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/token/verification/AccessTokenVerifierImpl.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/CredentialQueryResolverImplTest.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/PresentationGeneratorImplTest.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/defaults/InMemoryCredentialStoreTest.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/token/verification/AccessTokenVerifierImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ResolutionApiComponentTest.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/generator/PresentationCreatorRegistry.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/generator/PresentationGenerator.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/model/IdentityResource.java

- fix: several minor improvements and fixes
- add "audience" parameter
This is a collection PR for the following minor improvements/fixes:
- `LdpPresentationCreator`: add proof purpose and verification method properties when signing LDP-VPs
- `CredentialQueryResolver`: execute actual database query when comparing issuer and prover scope. This was necessary because the in-memory predicate does not properly map the credential types
- `PresentationGenerator`: pass additional data to VP creators (e.g. "aud" for JWT-VPs)
- `AccessTokenVerifierImpl`: only issue a warning when proof-of-possession was not established. This is a specific issue when the Participant ID and the token subject are not equal
- add some source doc and comments
These issues arose during end-to-end testing and setting up a …

fix: various smaller fixes for IATP

---

DEPENDENCIES
core/identity-hub-api/src/main/java/org/eclipse/edc/identityservice/api/PresentationApiExtension.java
core/identity-hub-api/src/main/java/org/eclipse/edc/identityservice/api/v1/PresentationApiController.java
core/identity-hub-api/src/test/java/org/eclipse/edc/identityservice/api/v1/PresentationApiControllerTest.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/PresentationCreatorRegistryImpl.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/VerifiablePresentationServiceImpl.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/creators/JwtPresentationGenerator.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationGenerator.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/VerifiablePresentationServiceImplTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/JwtPresentationGeneratorTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationGeneratorTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/PresentationGeneratorTest.java
docs/developer/architecture/identity-trust-protocol/identity-and-trust-modules.md
docs/developer/architecture/identity-trust-protocol/identity.hub.architecture.md
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ResolutionApiComponentTest.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/generator/PresentationCreatorRegistry.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/generator/PresentationGenerator.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/generator/VerifiablePresentationService.java

This PR renames a few classes and updates the architecture doc.

refactor: rename classes 

---

core/identity-hub-credentials/build.gradle.kts
core/identity-hub-did/build.gradle.kts
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidResourceManager.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidServicesExtension.java
core/identity-hub-did/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
core/identity-hub-did/src/main/resources/did.json
core/identity-hub-did/src/test/resources/did.json
docs/developer/architecture/identity-trust-protocol/identity.hub.architecture.md
resources/checkstyle-config.xml
resources/checkstyle-suppressions.xml
resources/suppressions.xml
settings.gradle.kts
spi/identity-hub-did-spi/build.gradle.kts
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidDocumentPublisher.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidDocumentService.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/model/DidResource.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/model/DidState.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/package-info.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/store/DidResourceStore.java

This PR adds two modules:
- `identity-hub-did-spi`: SPI module, contains model classes and interfaces
- `identity-hub-did`: implementation module, currently empty
Add module structure, even if that is currently empty, to enable subsequent implementation tasks.
- the architecture document was updated to reflect the SPI classes

feat: add DID module 

---

DEPENDENCIES
core/identity-hub-api/src/main/java/org/eclipse/edc/identityservice/api/PresentationApiExtension.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentPublisherRegistryImpl.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidServicesExtension.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/defaults/DidDefaultServicesExtension.java
extensions/did/local-did-publisher/build.gradle.kts
extensions/did/local-did-publisher/src/main/java/org/eclipse/edc/identityhub/publisher/did/local/DidWebController.java
extensions/did/local-did-publisher/src/main/java/org/eclipse/edc/identityhub/publisher/did/local/LocalDidPublisher.java
extensions/did/local-did-publisher/src/main/java/org/eclipse/edc/identityhub/publisher/did/local/LocalDidPublisherExtension.java
extensions/did/local-did-publisher/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/did/local-did-publisher/src/test/java/org/eclipse/edc/identityhub/publisher/did/local/DidWebControllerTest.java
extensions/did/local-did-publisher/src/test/java/org/eclipse/edc/identityhub/publisher/did/local/LocalDidPublisherTest.java
extensions/did/local-did-publisher/src/test/java/org/eclipse/edc/identityhub/publisher/did/local/TestFunctions.java
launcher/build.gradle.kts
settings.gradle.kts
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidConstants.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidDocumentPublisher.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidDocumentPublisherRegistry.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidWebParser.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/model/DidResource.java
spi/identity-hub-did-spi/src/test/java/org/eclipse/edc/identithub/did/spi/DidWebParserTest.java

This PR adds a local `DidPublisher`, that is intended for testing and demo purposes to provide a working out-of-the-box experience.
The `LocalDidPublisher` "publishes" DID documents by simply modifying their `DidState` and setting it to `PUBLISHED`. Then, there is the 
`DidWebController`, which serves DID documents by taking the request URL and converting it to a DID.  For example if the controller's context is configured as
```properties
web.http.did.port=10100
web.http.did.path="/"
```
then the `DidWebController` would accept all paths starting with "/". That means, that DID documents with the following IDs would be returned, provided they are found in the database:
```
http://localhost:10100/did/someone/say/cookie                      --> …
```

feat: implement local DidPublisher

---

core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/ApiSchema.java
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApi.java
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApiController.java
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/validation/PresentationQueryValidator.java
core/identity-hub-api/src/test/java/org/eclipse/edc/identityservice/api/v1/PresentationApiControllerTest.java
core/identity-hub-api/src/test/java/org/eclipse/edc/identityservice/api/validation/PresentationQueryValidatorTest.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentPublisherRegistryImpl.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidServicesExtension.java
core/identity-hub-did/src/test/java/org/eclipse/edc/identityhub/did/DidDocumentPublisherRegistryImplTest.java
core/identity-hub-did/src/test/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImplTest.java
extensions/did/did-management-api/build.gradle.kts
extensions/did/did-management-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/DidManagementApiExtension.java
extensions/did/did-management-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApi.java
extensions/did/did-management-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApiController.java
extensions/did/did-management-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidRequestPayload.java
extensions/did/did-management-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/validation/DidRequestValidator.java
extensions/did/did-management-api/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/did/did-management-api/src/test/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApiControllerTest.java
extensions/did/local-did-publisher/src/main/java/org/eclipse/edc/identityhub/publisher/did/local/LocalDidPublisher.java
extensions/did/local-did-publisher/src/test/java/org/eclipse/edc/identityhub/publisher/did/local/LocalDidPublisherTest.java
launcher/build.gradle.kts
settings.gradle.kts
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidDocumentPublisher.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidDocumentPublisherRegistry.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidDocumentService.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/model/DidResource.java

This PR adds a CRUD management API for Decentralized Identifiers (DID). More specifically, it adds:
- a `DidManagementApi` that contains swagger annotations
- a `DidManagementApiController` that implements the REST interface
- a `DidDocumentServiceImpl`, that acts as aggregate service and creates the transaction boundary
- a `DidRequestValidator`, that validates the structure of a `DidDocument`
- tests
- some refactoring w.r.t. package names 
For managing DID documents
- Although internally the IdentityHub manages `DidResource` objects, the Management API only exposes `DidDocument` objects (which are a part of `DidResources`) and provides specific endpoints for "actions", such as `publish`. This is done because those actions are synchronous, which means there is no state machine that …

feat: implement DID management API

---

.github/workflows/apidoc.yaml
.github/workflows/release-identityhub.yml
DEPENDENCIES
build.gradle.kts
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApi.java
extensions/did/did-management-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApiController.java
extensions/did/did-management-api/src/test/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApiControllerTest.java

Adds a GH Actions workflow that publishes the (generated) OpenAPI spec to SwaggerHub.
Documentation
I also converted all `DELETE /...` endpoints to `POST /.../delete` endpoints, because SwaggerHub complained that "DELETE calls cannot contain request bodies". The spec isn't super specific on the topic and doesn't explicitly forbid it, but upon further investigation, I read that some load balancers and API gateways may discard or even reject DELETE requests with a 400 that contain a body.
Closes #206

chore: publish IdentityHub API to SwaggerHub

---

extensions/common/security/build.gradle.kts
extensions/common/security/src/main/java/org/eclipse/edc/identityhub/security/KeyPairGenerator.java
extensions/common/security/src/test/java/org/eclipse/edc/identityhub/security/KeyPairGeneratorTest.java
settings.gradle.kts

adds an implementation of a `KeyPairGenerator` as lib class
For various subsequent development steps we need to generate keys.
Closes #221

feat: create KeyPairGenerator

---

core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryCredentialStore.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryEntityStore.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryParticipantContextStore.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/defaults/InMemoryCredentialStoreTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/defaults/InMemoryParticipantContextStoreTest.java
extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlCredentialStore.java
extensions/store/sql/identity-hub-participantcontext-store-sql/build.gradle.kts
extensions/store/sql/identity-hub-participantcontext-store-sql/docs/schema.sql
extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/BaseSqlDialectStatements.java
extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/ParticipantContextStoreStatements.java
extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/SqlParticipantContextStore.java
extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/SqlParticipantContextStoreExtension.java
extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/schema/postgres/ParticipantContextMapping.java
extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/schema/postgres/PostgresDialectStatements.java
extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/store/sql/identity-hub-participantcontext-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlParticipantContextStoreTest.java
settings.gradle.kts
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/participant/ParticipantContext.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/participant/ParticipantContextState.java
spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/model/participant/ParticipantContextTest.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/CredentialStore.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/ParticipantContextStore.java
spi/identity-hub-store-spi/src/testFixtures/java/org/eclipse/edc/identityhub/store/test/CredentialStoreTestBase.java
spi/identity-hub-store-spi/src/testFixtures/java/org/eclipse/edc/identityhub/store/test/ParticipantContextStoreTestBase.java

Adds a `ParticipantContextStore` interface, and one implementation each for in-mem and Postgres.
Preparatory work for subsequent development steps.
A common base class for in-mem CRUD stores `InMemoryEntityStore` has been created. ~~To that end, another interface `Identifiable` was added, which all entities must implement.~~
Closes #223

feat: add ParticipantContextStore

---

extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/schema/postgres/CredentialJsonMapping.java
extensions/store/sql/identity-hub-did-store-sql/src/main/java/org/eclipse/edc/identityhub/did/store/sql/schema/postgres/DidDocumentMapping.java

adapts the code base to using the newly introduced `JsonFieldTranslator`.
keep in-step with upstream EDC

fix: incorporate JsonFieldTranslator

---

core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-did/src/test/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImplTest.java
extensions/did/did-management-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApi.java
extensions/did/did-management-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApiController.java
extensions/did/did-management-api/src/test/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApiControllerTest.java
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/DidDocumentService.java

This PR removes generic endpoints from the DidManagementAPI, such as create, update or delete. Instead, they have been replaced with more focused endpoints for adding `serviceEndpoint` entries 
to a DID document.
For the purposes of IdentityHub, the DID document is a fully managed piece of information, that is merely a representation of a particular participant. Thus, 
manually modifying that document can cause inconsistencies.
- the `DidDocumentService` has been adapted too, to reflect those changes.
Closes #220

feat: make DidManagementApi more explicit

---

core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/CredentialQueryResolverImplTest.java
extensions/store/sql/identity-hub-credentials-store-sql/docs/schema.sql
extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/BaseSqlDialectStatements.java
extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/CredentialStoreStatements.java
extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlCredentialStore.java
extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/schema/postgres/VerifiableCredentialResourceMapping.java
extensions/store/sql/identity-hub-did-store-sql/docs/schema.sql
extensions/store/sql/identity-hub-did-store-sql/src/main/java/org/eclipse/edc/identityhub/did/store/sql/BaseSqlDialectStatements.java
extensions/store/sql/identity-hub-did-store-sql/src/main/java/org/eclipse/edc/identityhub/did/store/sql/DidResourceStatements.java
extensions/store/sql/identity-hub-did-store-sql/src/main/java/org/eclipse/edc/identityhub/did/store/sql/SqlDidResourceStore.java
extensions/store/sql/identity-hub-did-store-sql/src/main/java/org/eclipse/edc/identityhub/did/store/sql/schema/postgres/DidResourceMapping.java
spi/identity-hub-did-spi/build.gradle.kts
spi/identity-hub-did-spi/src/main/java/org/eclipse/edc/identithub/did/spi/model/DidResource.java
spi/identity-hub-did-spi/src/testFixtures/java/org/eclipse/edc/identityhub/did/store/test/DidResourceStoreTestBase.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/model/IdentityResource.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/model/KeyPairResource.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/model/ParticipantResource.java
spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/spi/store/model/VerifiableCredentialResource.java
spi/identity-hub-store-spi/src/test/java/org/eclipse/edc/identityhub/spi/store/model/VerifiableCredentialResourceTest.java
spi/identity-hub-store-spi/src/testFixtures/java/org/eclipse/edc/identityhub/store/test/CredentialStoreTestBase.java

Adds a `participantId` property to all resources, that are owned by a `ParticipantContext`
to enable multi-user administration
Closes #240 

feat: add participantId to all resources

---

DEPENDENCIES
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/ApiSchema.java
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApi.java
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApiController.java
core/identity-hub-api/src/test/java/org/eclipse/edc/identityservice/api/v1/PresentationApiControllerTest.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemorySignatureSuiteRegistry.java
core/identity-hub-credentials/src/main/resources/iatp.v08.json
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationGeneratorTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ResolutionApiComponentTest.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/resolution/CredentialQueryResolver.java

Adapt after iatp changes in https://github.com/eclipse-edc/Connector/pull/3808:
- presentation query endpoint now speaks JSON-LD
- enriched the openapi definition

chore: fixes after IATP changes

---

e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/DidManagementApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
extensions/api/identityhub-api-authorization/src/main/java/org/eclipse/edc/identityhub/api/authorization/AuthorizationServiceImpl.java
extensions/api/identityhub-api-authorization/src/test/java/org/eclipse/edc/identityhub/api/authorization/AuthorizationServiceImplTest.java

This PR adds an override to the `AuthorizationService` which grants access to all resources to the `"admin"` role.
In practice, this gives all permissions to the super-user.
In managed situations this is needed, e.g. as a rescue measure when the credentials of a service principal are compromised or lost, or as 
deployment feature when certain data is to be pre-seeded on behalf of the participant.
Ultimately, we could think about a more elaborate/more complicated role/permission scheme that allows impersonation, but for now
this seems good enough.
Closes #247 …

feat: add permission override for super-user/admin role

---

core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextExtension.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImplTest.java
extensions/api/identityhub-management-api-configuration/build.gradle.kts
extensions/api/identityhub-management-api-configuration/src/main/java/org/eclipse/edc/identityhub/api/configuration/ManagementApiConfigurationExtension.java
extensions/api/identityhub-management-api-configuration/src/test/java/org/eclipse/edc/identityhub/api/configuration/ManagementApiConfigurationExtensionTest.java

This PR adds a config parameter `edc.ih.api.superuser.key` that allows to override the
automatically generated API key for the SuperUser
In automated deployment scenarios it may be virtually impossible to `grep` the log output of a container/pod
to obtain the API key. Therefor a way to explicitly set / override it is very helpful.
- API keys must still follow the format `base64("super-user").<random-string>`, otherwise a warning is logged
Closes #249

feat: add API key override for Super-User

---

e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ManagementApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
extensions/api/participant-context-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/participantcontext/v1/ParticipantContextApi.java
extensions/api/participant-context-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/participantcontext/v1/ParticipantContextApiController.java
extensions/api/participant-context-mgmt-api/src/test/java/org/eclipse/edc/identityhub/api/participantcontext/v1/ParticipantContextApiControllerTest.java

This PR adds an endpoint `PUT /v1/participants/<participantId>/roles` that allows the super-user
to update the roles of a participant
Extensibility of the RBAC concept
Closes #252

feat: add endpoint to update roles of a ParticipantContext

---

extensions/api/participant-context-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/participantcontext/v1/ParticipantContextApiController.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/participant/ParticipantContext.java

This PR adds a method to explicitly set the roles of a `ParticipantContext`
updating roles with `getRoles().clear()` and `getRoles().addAll()` will fail on immutable lists.

fix: explicit modification of roles

---

DEPENDENCIES
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/CredentialResourceLookup.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryCredentialStore.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryEntityStore.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryKeyPairResourceStore.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryParticipantContextStore.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/defaults/DidDefaultServicesExtension.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/defaults/InMemoryDidResourceStore.java
core/identity-hub-did/src/test/java/org/eclipse/edc/identityhub/did/defaults/InMemoryDidResourceStoreTest.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceExtension.java

This PR adapts to the latest changes in upstream EDC, most notably w.r.t. the 
`CriterionOperatorRegistry` and the `PropertyLookup` functions.
Compile errors

chore: incorporate latest changes of EDC

---

DEPENDENCIES
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidServicesExtension.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairEventPublisher.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceExtension.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImpl.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventCoordinator.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventPublisher.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextExtension.java
core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventCoordinatorTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/events/participant/ParticipantContextCreated.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/events/participant/ParticipantContextEvent.java

This PR implements the `ParticipantContextEventCoordinator`, whos job it is to handle `ParticipantContextCreated` events in a coordinated (= linear) way.
First, the DID document is created, and then the KeyPair is added, causing the DID Document to get updated.
The current implementation of the `EventRouter` does not lend itself well to handling dependent events.
- An alternative route, i.e. an `EventQueue` was explored, but while it most likely would have also solved this problem, it was deemed impractical and hard to debug. 
- requires https://github.com/eclipse-edc/Connector/pull/3833
- renamed all the `*ListenerImpl`s to `*Publisher`
Closes #
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-re …

feat: implement ParticipantContextEventCoordinator

---

DEPENDENCIES
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/VerifiablePresentationServiceImpl.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationGenerator.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationGeneratorTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/PresentationGeneratorTest.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java

This PR adds the `controller` property to generated LDP-VPs, as well as composes
the `key-id` property using that controller prop.
Key resolution, verification

fix: add controller property to generated VP

---

core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApiController.java
docs/developer/architecture/mgmt-api.security.md
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiComponentTest.java
extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApiController.java
extensions/api/keypair-mgmt-api/src/test/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApiControllerTest.java
extensions/api/participant-context-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/participantcontext/v1/ParticipantContextApiController.java
extensions/api/participant-context-mgmt-api/src/test/java/org/eclipse/edc/identityhub/api/participantcontext/v1/ParticipantContextApiControllerTest.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/ParticipantContextId.java

This PR changes behavior of the controllers to that the `participantId` passed in the request path segment is now assumed to be base64-url encoded. 
Avoid collision when the actual `participantId` contains characters that should not be encoded when calling the APIs. 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md). …

feat: base64-url encoded `participantId` in API controllers

---

extensions/api/verifiable-credential-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/VerifiableCredentialApiExtension.java
extensions/api/verifiable-credential-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/GetAllCredentialsApiController.java

this PR correctly registers the "get-all" controller for VCs
previously it had been forgotten.

fix: register VC get-all controller

---

core/identity-hub-api/build.gradle.kts
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApiController.java
gradle/libs.versions.toml

Read audience from `iss` claim instead of deprecated `client_id`.
`client_id` is not used anymore.
Closes #276 

fix: get audience from 'iss' claim instead of deprecated 'client_id'

---

core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/PresentationCreatorRegistryImpl.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/VerifiablePresentationServiceImpl.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/creators/JwtPresentationGenerator.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationGenerator.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/creators/PresentationGeneratorConstants.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/PresentationCreatorRegistryImplTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/VerifiablePresentationServiceImplTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/JwtPresentationGeneratorTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationGeneratorTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/PresentationGeneratorTest.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/generator/PresentationGenerator.java

Add missing `kid` header in output of `JwtPresentationGenerator`.
`kid` is used by the counterparty to resolve the public key required to validate the VP.

fix: add missing `kid` header in `JwtPresentationGenerator`

---

DEPENDENCIES
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/CredentialResourceLookup.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/EdcScopeToCriterionTransformer.java
spi/identity-hub-store-spi/src/testFixtures/java/org/eclipse/edc/identityhub/store/test/CredentialStoreTestBase.java

Use class argument name and serialized name for the `type` and `credentialSubject` properties of the `VerifiableCredential` object.
This is required to have a consistent way to query for a VC independently on the type of VC store (in-mem store uses reflection while PostgreSQL store will work on the serialized json structure. …

fix: use `type` and `credentialSubject` properties in `VerifiableCredential`

---

DEPENDENCIES
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImpl.java
core/identity-hub-keypairs/src/test/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ManagementApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApi.java
extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApiController.java
extensions/api/keypair-mgmt-api/src/test/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApiControllerTest.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/KeyPairService.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/KeyPairResource.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/participant/KeyDescriptor.java

This PR fixes the handling of the KeyPairResource's ACTIVE state
There was no way to move the key pair to the ACTIVE state before.
Closes #284

fix: set keypair to ACTIVE

---

core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemoryEntityStore.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImpl.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ManagementApiEndToEndTest.java
extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApiController.java
spi/identity-hub-did-spi/src/testFixtures/java/org/eclipse/edc/identityhub/did/store/test/DidResourceStoreTestBase.java
spi/identity-hub-store-spi/src/testFixtures/java/org/eclipse/edc/identityhub/store/test/CredentialStoreTestBase.java
spi/identity-hub-store-spi/src/testFixtures/java/org/eclipse/edc/identityhub/store/test/KeyPairResourceStoreTestBase.java
spi/identity-hub-store-spi/src/testFixtures/java/org/eclipse/edc/identityhub/store/test/ParticipantContextStoreTestBase.java

This PR adapts the behaviour of the `InMem-` stores so that it is identical to the `Sql-` stores. 
In particular, the in-mem stores joined multiple `Criterion` filters with a logical _or_, whereas the SQL stores 
use an _and_. 
Achieve identical behaviour.
- I updated some files to use the `ParticipantResource.queryByParticipantId()` factory method to query by participant ID.

fix: make InMem- and SQL stores behave the same

---

DEPENDENCIES
extensions/api/did-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApi.java
extensions/api/did-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/DidManagementApiController.java
extensions/api/did-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/GetAllDidsApi.java
extensions/api/did-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/GetAllDidsApiController.java
extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/GetAllKeyPairsApi.java
extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/GetAllKeyPairsApiController.java
extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApi.java
extensions/api/keypair-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/KeyPairResourceApiController.java
extensions/api/participant-context-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/participantcontext/v1/ParticipantContextApi.java
extensions/api/participant-context-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/participantcontext/v1/ParticipantContextApiController.java
extensions/api/verifiable-credential-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/GetAllCredentialsApi.java
extensions/api/verifiable-credential-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/GetAllCredentialsApiController.java
extensions/api/verifiable-credential-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/VerifiableCredentialsApi.java
extensions/api/verifiable-credential-mgmt-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/VerifiableCredentialsApiController.java

Prevent API operation name collision in merged OpenAPI file for Management API.
Some API Gateway such as Azure API Management does not support multiple API operations having the same name in the same openapi file.

docs: prevent collision in operation names in IdentityHub management API

---

core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/CredentialQueryResolverImpl.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/CredentialQueryResolverImplTest.java

Fixes the case when there are multiple `scopes` and after the Scope -> Criterion mapping the query is executed using `and` logical operator. We don't support yet a way to express `or`, so we ended up doing multiple queries one for each scope

chore: fixes query in case of multiple scopes

---

DEPENDENCIES
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/creators/JwtPresentationGenerator.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/JwtPresentationGeneratorTest.java

Align claim types of JWT presentation with `JwtPresentationVerifier`.
Fix compatibility with `JwtPresentationVerifier`.

fix: align JWT presentation claim type with `JwtPresentationVerifier`

---

DEPENDENCIES
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
extensions/store/sql/identity-hub-credentials-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlCredentialsStoreTest.java
extensions/store/sql/identity-hub-did-store-sql/src/test/java/org/eclipse/edc/identityhub/did/store/sql/SqlDidResourceStoreTest.java
extensions/store/sql/identity-hub-keypair-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/keypair/SqlKeyPairResourceStoreTest.java
extensions/store/sql/identity-hub-participantcontext-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlParticipantContextStoreTest.java
gradle/libs.versions.toml
spi/identity-hub-spi/build.gradle.kts
spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/events/diddocument/DidDocumentPublishedTest.java
spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/events/diddocument/DidDocumentUnpublishedTest.java
spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/events/keypair/KeyPairAddedTest.java
spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/events/keypair/KeyPairRevokedTest.java
spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/events/keypair/KeyPairRotatedTest.java
spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/events/participant/ParticipantContextCreatedTest.java
spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/events/participant/ParticipantContextDeletedTest.java
spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/events/participant/ParticipantContextUpdatedTest.java

Uses the `JacksonTypeManager` now instead of the `TypeManager`, which is now an interface

fix: use JacksonTypeManager instead

---

.github/workflows/verify.yaml
DEPENDENCIES
build.gradle.kts
core/identity-hub-api/build.gradle.kts
core/identity-hub-credentials/build.gradle.kts
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationGenerator.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/InMemorySignatureSuiteRegistry.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/core/creators/LdpPresentationGeneratorTest.java
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
spi/identity-hub-spi/build.gradle.kts

This PR updates the code base to comply with the latest changes of upstream EDC that were made after the bump
of the `iron-verifiable-credentials` library. no functional changes, only adopted a new SPI.
bump in iron-verifiable-credentials

chore: update codebase to work with latest iron-vc impl

---

DEPENDENCIES
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImplTest.java

Correctly sets the participant's DID when converting from ParticipantManifest -> ParticipantContext
Closes #347

fix: set DID when creating participant context

---

DEPENDENCIES
core/lib/credential-query-lib/src/main/java/org/eclipse/edc/identityhub/query/CredentialQueryResolverImpl.java

Avoids an NPE in the `CredentialQueryResolver`

fix: avoid NPE in credential resolver

---

core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairEventPublisher.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImpl.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/IdentityApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
extensions/api/identity-api/keypair-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/unstable/KeyPairResourceApiController.java
extensions/store/sql/identity-hub-keypair-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/keypair/SqlKeyPairResourceStore.java
spi/keypair-spi/src/main/java/org/eclipse/edc/identityhub/spi/keypair/events/KeyPairEvent.java
spi/keypair-spi/src/main/java/org/eclipse/edc/identityhub/spi/keypair/model/KeyPairResource.java
spi/keypair-spi/src/test/java/org/eclipse/edc/identityhub/spi/keypair/events/KeyPairAddedTest.java
spi/keypair-spi/src/test/java/org/eclipse/edc/identityhub/spi/keypair/events/KeyPairRevokedTest.java
spi/keypair-spi/src/test/java/org/eclipse/edc/identityhub/spi/keypair/events/KeyPairRotatedTest.java
spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/KeyDescriptor.java

disentangles the `KeyPairResource#id` and `KeyPairResource#keyId`
avoid ID collisions in the future. the ID and the key ID were sometimes used interchangeably, which is not correct.
Closes #368

feat: disentangle `KeyPairResource#id` and `KeyPairResource#keyId`

---

DEPENDENCIES
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/DidManagementApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/IdentityApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java

Migrates E2E tests to the per-class model.
Adopting upstream changes, make E2E MUCH faster

fix: use per-class runtimes in E2E tests

---

DEPENDENCIES
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/lib/verifiable-presentation-lib/src/main/java/org/eclipse/edc/identithub/verifiablepresentation/PresentationCreatorRegistryImpl.java
core/lib/verifiable-presentation-lib/src/main/java/org/eclipse/edc/identithub/verifiablepresentation/generators/JwtPresentationGenerator.java
core/lib/verifiable-presentation-lib/src/main/java/org/eclipse/edc/identithub/verifiablepresentation/generators/LdpPresentationGenerator.java
core/lib/verifiable-presentation-lib/src/test/java/org/eclipse/edc/identithub/verifiablepresentation/PresentationCreatorRegistryImplTest.java
core/lib/verifiable-presentation-lib/src/test/java/org/eclipse/edc/identithub/verifiablepresentation/generators/JwtPresentationGeneratorTest.java
core/lib/verifiable-presentation-lib/src/test/java/org/eclipse/edc/identithub/verifiablepresentation/generators/LdpPresentationGeneratorTest.java
core/lib/verifiable-presentation-lib/src/test/java/org/eclipse/edc/identithub/verifiablepresentation/generators/PresentationGeneratorTest.java
spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/generator/PresentationGenerator.java

- **allow multiple issuers (wip)**
- **fix test**
- **remove old property**
instead of taking IH's issuer ID from a static config value (`edc.ih.iam.issuer.id`), it now takes the DID from the participant context, for whom the presentation query was issued.
For example, if "Company B" queries "Company A"'s IdentityHub for credentials, then the VP issuer would be the DID of "Company A".
With the ability to host multiple participant contexts (="tenants") the issuer ID cannot be static anymore.
Closes #361 
_Please be sure to take a look at the [contributing …

feat: allow multiple VP isuers

---

DEPENDENCIES
docs/developer/README.md
docs/developer/decision-records/README.md

Provides a root `README` for developer docs
Fix 404 in the documentation site.
As reported in https://github.com/eclipse-edc/docs/issues/153

docs: provide developer docs readme file

---

core/lib/credential-query-lib/src/main/java/org/eclipse/edc/identityhub/query/CredentialQueryResolverImpl.java
core/lib/credential-query-lib/src/test/java/org/eclipse/edc/identityhub/query/CredentialQueryResolverImplTest.java

makes the `scope` parameter of a `PresentationQueryMessage` optional, and adapts the `CredentialQueryResolver` accordingly.
- if request scopes are provided, they must match the access token scopes. 
- if no request scopes are provided, all credentials that are selected by the access token scopes are returned
several shortcuts have been implemented, to save some database communication.
DCP specifies the `scope` parameter as optional
Contributes https://github.com/eclipse-edc/Connector/issues/4322
_Please be sure to take a look at the [contributing …

fix: make scope parameter of PresentationQuery optional

---

DEPENDENCIES
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/lib/accesstoken-lib/src/main/java/org/eclipse/edc/identityhub/accesstoken/verification/AccessTokenVerifierImpl.java
core/lib/accesstoken-lib/src/test/java/org/eclipse/edc/identityhub/accesstoken/verification/AccessTokenVerifierImplComponentTest.java
core/lib/accesstoken-lib/src/test/java/org/eclipse/edc/identityhub/accesstoken/verification/AccessTokenVerifierImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java

enable proof of possession check on token validation
Closes #402 

feat: enable proof of possession check on token validation

---

DEPENDENCIES
core/identity-hub-core/build.gradle.kts
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-did/build.gradle.kts
core/identity-hub-keypairs/build.gradle.kts
core/identity-hub-participants/build.gradle.kts
core/lib/verifiable-presentation-lib/build.gradle.kts
core/lib/verifiable-presentation-lib/src/main/java/org/eclipse/edc/identithub/verifiablepresentation/generators/JwtPresentationGenerator.java
core/lib/verifiable-presentation-lib/src/test/java/org/eclipse/edc/identithub/verifiablepresentation/generators/JwtPresentationGeneratorTest.java
gradle/libs.versions.toml
spi/verifiable-credential-spi/build.gradle.kts

adapts the code base to use the new `JwsSignerProvider` introduced recently in upstream EDC
compile errors
also updates the version catalog entry `edc.common.crypto` -> `edc.libs.common.crypto` for consistency

fix: use the new JwsSignerProvider interface

---

README.md

Adds a warning about old versions to the README
to dissuade people from using vastly outdated code.
depends on [this fix](#419)

chore: put warning in readme

---

DEPENDENCIES
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/lib/credential-query-lib/src/main/java/org/eclipse/edc/identityhub/query/CredentialQueryResolverImpl.java
core/lib/credential-query-lib/src/test/java/org/eclipse/edc/identityhub/query/CredentialQueryResolverImplTest.java
core/lib/verifiable-presentation-lib/src/main/java/org/eclipse/edc/identithub/verifiablecredential/CredentialStatusCheckServiceImpl.java
core/lib/verifiable-presentation-lib/src/test/java/org/eclipse/edc/identithub/verifiablecredential/CredentialStatusCheckServiceImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java

updates IH to use the `REvocationServiceRegistry`
compile errors

fix: use RevocationServiceRegistry (new EDC feature)

---

.github/workflows/verify.yaml
README.md
core/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
core/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApi.java
core/presentation-api/src/main/resources/presentation-api-version.json
docs/developer/architecture/identity-trust-protocol/identity-hub-modules.md
docs/developer/architecture/identityhub-apis.md
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubRuntimeConfiguration.java
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/IdentityHubApiContext.java

deprecates the `resolution` api context and replaces all occurrences with `presentation`. if `web.http.presentation.*` is configured, that overrides `resolution`. if only `resolution` is configured, then a warning is issued.
consistent naming.
Closes #431

chore: deprecate resolution api context

---

core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextExtension.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java

defensively checks if another ParticipantContext already exists with the same DID when creating ParticipantContexts
defensive checks are better than relying on the database operation failing with a PK violation

feat: check if DID exists before creating a participant

---

docs/developer/decision-records/2024-08-23-identity_hub_identity_write_credentials_api/README.md
docs/developer/decision-records/README.md

DR for adding endpoints to create/update VCs.
Offers a way to add credentials into the Identity Hub.
Contributes #434 

docs: adds decision record for VC create/update API

---

DEPENDENCIES
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/api/identity-api/keypair-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/unstable/KeyPairResourceApi.java
extensions/api/identity-api/validators/build.gradle.kts
extensions/api/identity-api/validators/src/main/java/org/eclipse/edc/identityhub/api/v1/validation/VerifiableCredentialManifestValidator.java
extensions/api/identity-api/validators/src/test/java/org/eclipse/edc/identityhub/api/v1/validation/VerifiableCredentialManifestValidatorTest.java
extensions/api/identity-api/verifiable-credentials-api/build.gradle.kts
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/VerifiableCredentialApiExtension.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApi.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/transformer/VerifiableCredentialManifestToVerifiableCredentialResourceTransformer.java
extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiControllerTest.java
extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/transformer/VerifiableCredentialManifestToVerifiableCredentialResourceTransformerTest.java
spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/IdentityResource.java
spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/VerifiableCredentialManifest.java
spi/verifiable-credential-spi/src/test/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/VerifiableCredentialManifestTest.java

Adds credential create/update endpoints in identity API context.
Enables creation/update of VC from the identity APIs.
Closes #433 

feat: Credential create/update API

---

core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-did/src/test/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImplTest.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventCoordinator.java
core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventCoordinatorTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java

aligns the behaviour of the `createParticipantContext` operation with [Decision Record 2024-09-02](https://github.com/eclipse-edc/IdentityHub/tree/main/docs/developer/decision-records/2024-09-02-resource-operations).
have consistent behaviour

chore: align createParticipantContext operation with DR

---

core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidServicesExtension.java
core/identity-hub-did/src/test/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImplTest.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceExtension.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImpl.java
core/identity-hub-keypairs/src/test/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImplTest.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventCoordinator.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventPublisher.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextExtension.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/DidManagementApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
extensions/did/local-did-publisher/src/main/java/org/eclipse/edc/identityhub/publisher/did/local/LocalDidPublisher.java
extensions/did/local-did-publisher/src/test/java/org/eclipse/edc/identityhub/publisher/did/local/LocalDidPublisherTest.java
spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/events/ParticipantContextDeleting.java
spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/events/ParticipantContextListener.java

Aligns the code base with [this decision-record](https://github.com/eclipse-edc/IdentityHub/tree/main/docs/developer/decision-records/2024-09-02-resource-operations#2-deleting-a-participant-context-deleteparticipantcontext), specifically the delete-participant action.
In doing so, the following changes were made
- new event type `ParticipantContextDeleting` was introduced to signal an impending deletion. This event is consumed by the `ParticipantContextEventCoordinator` that triggers the `DidDocumentService` to unpublish and delete the DID Docs, and the `KeyPairService` to revoke the key.
- the `DidDocumentService` does **not** consume the `ParticipantContextDeleted` event anymore, because it gets invoked directly by the coordinator
- `KeyPairServiceImpl`: added transaction context
- …

chore: align deleteParticipantContext with DR

---

core/identity-hub-did/build.gradle.kts
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidServicesExtension.java
core/identity-hub-did/src/test/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImplTest.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextCoordinatorExtension.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextExtension.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
core/identity-hub-participants/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/DidManagementApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java

aligns DID operations (publish, unpublish) with [this decision-record](https://github.com/eclipse-edc/IdentityHub/tree/main/docs/developer/decision-records/2024-09-02-resource-operations#did-document-operations).
Alignment with D-R

chore: align DID operations with DR

---

core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidServicesExtension.java
core/identity-hub-did/src/test/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImplTest.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairEventPublisher.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImpl.java
core/identity-hub-keypairs/src/test/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImplTest.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventCoordinator.java
core/lib/keypair-lib/src/test/java/org/eclipse/edc/identityhub/publickey/KeyPairResourcePublicKeyResolverTest.java
core/lib/verifiable-presentation-lib/src/main/java/org/eclipse/edc/identithub/verifiablepresentation/PresentationCreatorRegistryImpl.java
core/lib/verifiable-presentation-lib/src/test/java/org/eclipse/edc/identithub/verifiablepresentation/PresentationCreatorRegistryImplTest.java
docs/developer/decision-records/2024-09-02-resource-operations/README.md
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/api/identity-api/keypair-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/unstable/KeyPairResourceApiController.java
extensions/api/identityhub-api-authorization/src/main/java/org/eclipse/edc/identityhub/api/authorization/AuthorizationServiceImpl.java
extensions/store/sql/identity-hub-keypair-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/keypair/BaseSqlDialectStatements.java
extensions/store/sql/identity-hub-keypair-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/keypair/KeyPairResourceStoreStatements.java
extensions/store/sql/identity-hub-keypair-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/keypair/SqlKeyPairResourceStore.java
extensions/store/sql/identity-hub-keypair-store-sql/src/main/resources/keypairs-schema.sql
spi/identity-hub-store-spi/src/testFixtures/java/org/eclipse/edc/identityhub/store/test/KeyPairResourceStoreTestBase.java
spi/keypair-spi/src/main/java/org/eclipse/edc/identityhub/spi/keypair/KeyPairService.java
spi/keypair-spi/src/main/java/org/eclipse/edc/identityhub/spi/keypair/events/KeyPairActivated.java
spi/keypair-spi/src/main/java/org/eclipse/edc/identityhub/spi/keypair/events/KeyPairEventListener.java
spi/keypair-spi/src/main/java/org/eclipse/edc/identityhub/spi/keypair/model/KeyPairResource.java
spi/keypair-spi/src/main/java/org/eclipse/edc/identityhub/spi/keypair/model/KeyPairState.java

Aligns the "active-key" operation with the decision record
- adds the `KeyPairActivated` event (and associated methods), which is consumed by the `DidDocumentService`
- adds a `keyContext` field to the `KeyPairResource` (and the associated DB schema) to track the "context" of the key, e.g. `"JsonWebKey2020"`
- renames `KeyPairStates#ACTIVE` to `KeyPairStates#ACTIVATED` for consistency
- the `PArticipantContextEventCoordinator` emits a warning log if a participant is added and activated, but its only key is in the `"inactive"` state
- `KeyPairService`: when a key is added in the `active` state, the `activateKey` method is invoked in the same transaction
- `DidDocumentService` reacts to the `KeyPairActivated` event instead of `KeyPairAdded` …

chore: align activate-key with D-R

---

core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceExtension.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImpl.java
core/identity-hub-keypairs/src/test/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java

aligns the `activateKeyPair` operation with the [decision-record](https://github.com/eclipse-edc/IdentityHub/tree/main/docs/developer/decision-records/2024-09-02-resource-operations)
- in essence, a check was added if the participant exists and is in the correct state. plus tests.

chore: align activate-keypair operation with DR

---

DEPENDENCIES
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-did/src/test/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImplTest.java
core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImpl.java
core/identity-hub-keypairs/src/test/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java

aligns the `rotate-keypair` action with the decision record
- added a `publish` action when activating a keypair. it wasn't there before. Note that this can lead to double publications when creating a participant context!

chore: align rotate keypair with dr

---

DEPENDENCIES
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextCoordinatorExtension.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventCoordinator.java
core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventCoordinatorTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/DidManagementApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java

This PR changes the `ParticipantContextEventCoordinator` such that `ParticipantContext` objects are _always_ created in the `inactive` state.
Then, keys are generated/added and possibly activated, and only _then_ is the `ParticipantContext` activated, causing the DID document to be published.
avoid multiple publications
Closes #455
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/ …

feat: activate ParticipantContext explicitly during creation

---

DEPENDENCIES
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/DidManagementApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
extensions/common/sts-account-provisioner/src/main/java/org/eclipse/edc/identityhub/common/provisioner/StsAccountProvisioner.java
extensions/common/sts-account-provisioner/src/main/java/org/eclipse/edc/identityhub/common/provisioner/StsAccountProvisionerExtension.java
extensions/common/sts-account-provisioner/src/test/java/org/eclipse/edc/identityhub/common/provisioner/StsAccountProvisionerTest.java

build: fix compilation

---

DEPENDENCIES
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/common/sts-account-provisioner/src/main/java/org/eclipse/edc/identityhub/common/provisioner/StsAccountProvisioner.java
extensions/common/sts-account-provisioner/src/test/java/org/eclipse/edc/identityhub/common/provisioner/StsAccountProvisionerTest.java
spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/AccountProvisioner.java
spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/ParticipantManifest.java

This PR adds an extensible Map to the `ParticipantManifest` to allow for additional parameters, such as customizing the alias under which the client_secret is stored in the vault.
avoid potential conflicts in the vault, consistent configuration
Closes #468

feat: allow customization of the STS Account's secret_alias

---

core/identity-hub-core/build.gradle.kts
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/DefaultServicesExtensionTest.java
core/lib/accesstoken-lib/build.gradle.kts
core/lib/accesstoken-lib/src/test/java/org/eclipse/edc/identityhub/accesstoken/verification/AccessTokenVerifierImplComponentTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubRuntimeConfiguration.java

add validation for the JWT Token IDs (`jti` claim) when verifying Access tokens.
to do that, the `JtiValidationRule` has been registered for the `"dcp-access-token"` validation context.
Note that by default this check is **deactivated** to avoid unexpected breakages in existing applications.
set `edc.iam.accesstoken.jti.validation=true` to enable it.
protection against replay attacks
Closes https://github.com/eclipse-edc/Connector/issues/3749
**DEPENDS ON https://github.com/eclipse-edc/Connector/pull/4560**

feat: validate 'jti' claims in `AccessTokenVerifier`

---

core/identity-hub-core/build.gradle.kts
core/lib/accesstoken-lib/build.gradle.kts
core/lib/verifiable-presentation-lib/build.gradle.kts
e2e-tests/runtimes/sts/build.gradle.kts
gradle/libs.versions.toml

fixes compile errors after the split of `token-core` into `token-lib`
compile errors :)

fix: compile error after EDC module split

---

e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
e2e-tests/bom-tests/src/test/java/org/eclipse/edc/test/bom/BomSmokeTests.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApi.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiControllerTest.java

The "query-by-credential-type" endpoint now gracefully handles the case where the credential type is not specified.
In that case, all credentials are returned (within the constraints of the default QuerySpec).
providing an incomplete criterion caused a Nullpointer Exception
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquet …

fix(api): gracefully handle missing type in query credential by type

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/DefaultServicesExtensionTest.java
e2e-tests/bom-tests/src/test/java/org/eclipse/edc/test/bom/BomSmokeTests.java
extensions/common/credential-watchdog/src/main/java/org/eclipse/edc/identityhub/common/credentialwatchdog/CredentialWatchdogExtension.java
extensions/common/credential-watchdog/src/test/java/org/eclipse/edc/identityhub/common/credentialwatchdog/CredentialWatchdogExtensionTest.java
extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlCredentialStoreExtension.java
extensions/store/sql/identity-hub-did-store-sql/src/main/java/org/eclipse/edc/identityhub/did/store/sql/SqlDidResourceStoreExtension.java
extensions/store/sql/identity-hub-keypair-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/keypair/SqlKeyPairResourceStoreExtension.java
extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/SqlParticipantContextStoreExtension.java
extensions/sts/sts-account-service-remote/src/main/java/org/eclipse/edc/identityhub/sts/accountservice/RemoteStsAccountServiceExtension.java

updates the code base to use configuration injection
less verbose code

feat: update codebase to use Config Injection

---

core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/PostgresSqlService.java
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/api/identity-api/participant-context-api/src/main/java/org/eclipse/edc/identityhub/api/participantcontext/v1/unstable/ParticipantContextApi.java
extensions/api/identity-api/participant-context-api/src/main/java/org/eclipse/edc/identityhub/api/participantcontext/v1/unstable/ParticipantContextApiController.java
extensions/api/identity-api/participant-context-api/src/test/java/org/eclipse/edc/identityhub/api/participantcontext/v1/unstable/ParticipantContextApiControllerTest.java
spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/ParticipantContextService.java
spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/CreateParticipantContextResponse.java

Introduce a `CreateParticipantContextResponse` record that replaces the generic `Map` used.
Add it to the openapi documentation (as currently it shows an empty body)
Enhance domain model, fix documentation
Closes #497

refactor: introduce record to represent create participant response

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGenerator.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGeneratorTest.java
extensions/protocols/dcp/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java

fix object mapper after upstream changes
compile errrors

chore: fix object mapper after upstream changes

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-core/src/main/resources/dcp.v1.0.jsonld
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/protocols/dcp/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/DcpApiConstants.java
extensions/protocols/dcp/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
extensions/protocols/dcp/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/validation/PresentationQueryValidator.java
extensions/protocols/dcp/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredential/PresentationApiController.java
extensions/protocols/dcp/presentation-api/src/test/java/org/eclipse/edc/identityservice/api/v1/PresentationApiControllerTest.java
extensions/protocols/dcp/presentation-api/src/test/java/org/eclipse/edc/identityservice/api/validation/PresentationQueryValidatorTest.java

adds support for dcp v1.0
The `JerseyJsonLdInterceptor` that automatically expand and compact JSON-LD has been removed. In the `PresentationController` since we need to guarantee backward compatibility we first manually expand JSON-LD which is an operation not tied to a specific protocol, then we detect the used namespace from the `@type` field of the expanded JSON-LD and we use the protocol specific transformer registry and JSON-LD scope for handling the request.   
dcp v1.0 support
Closes #531 
_Please be sure to …

feat: adds support for dcp v1.0

---

docs/developer/architecture/identity-trust-protocol/identity.hub.architecture.md

updates the IH architecture documentation stating that the `VerifiableCredentialResource` is re-used, and the areas of re-use.
documentation

docs: update architecture doc re/ VC resource

---

docs/developer/architecture/issuer/issuance/issuance.process.md
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
extensions/issuance/issuance-credentials/src/test/java/org/eclipse/edc/identityhub/issuance/credentials/attestation/AttestationPipelineImplTest.java
spi/issuance-credentials-spi/build.gradle.kts
spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/model/CredentialDefinition.java

this PR makes use of the existing `DataModelVersion` instead of declaring a new `DataModelType`
avoid duplication
had to fix a test, otherwise the CI would fail sometimes.

chore: re-use existing DataModelVersion

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/defaults/store/InMemoryCredentialStore.java
core/issuerservice/issuerservice-credential-revocation/build.gradle.kts
core/issuerservice/issuerservice-credential-revocation/src/main/java/org/eclipse/edc/issuerservice/statuslist/StatusListCredentialFactoryRegistryImpl.java
core/issuerservice/issuerservice-credential-revocation/src/main/java/org/eclipse/edc/issuerservice/statuslist/StatusListInfoFactoryRegistryImpl.java
core/issuerservice/issuerservice-credential-revocation/src/main/java/org/eclipse/edc/issuerservice/statuslist/StatusListServiceExtension.java
core/issuerservice/issuerservice-credential-revocation/src/main/java/org/eclipse/edc/issuerservice/statuslist/StatusListServiceImpl.java
core/issuerservice/issuerservice-credential-revocation/src/main/java/org/eclipse/edc/issuerservice/statuslist/bitstring/BitstringStatusInfo.java
core/issuerservice/issuerservice-credential-revocation/src/main/java/org/eclipse/edc/issuerservice/statuslist/bitstring/BitstringStatusListFactory.java
core/issuerservice/issuerservice-credential-revocation/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
core/issuerservice/issuerservice-credential-revocation/src/test/java/org/eclipse/edc/issuerservice/statuslist/StatusListServiceImplTest.java
core/issuerservice/issuerservice-credential-revocation/src/test/java/org/eclipse/edc/issuerservice/statuslist/TestData.java
core/issuerservice/issuerservice-credential-revocation/src/test/java/org/eclipse/edc/issuerservice/statuslist/bitstring/BitstringStatusListFactoryTest.java
extensions/issuance/issuance-credentials/src/test/java/org/eclipse/edc/identityhub/issuance/credentials/attestation/AttestationPipelineImplTest.java
extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlCredentialStore.java
settings.gradle.kts
spi/issuerservice/credential-revocation-spi/build.gradle.kts
spi/issuerservice/credential-revocation-spi/src/main/java/org/eclipse/edc/issuerservice/spi/statuslist/StatusListCredentialFactoryRegistry.java
spi/issuerservice/credential-revocation-spi/src/main/java/org/eclipse/edc/issuerservice/spi/statuslist/StatusListInfo.java
spi/issuerservice/credential-revocation-spi/src/main/java/org/eclipse/edc/issuerservice/spi/statuslist/StatusListInfoFactory.java
spi/issuerservice/credential-revocation-spi/src/main/java/org/eclipse/edc/issuerservice/spi/statuslist/StatusListInfoFactoryRegistry.java
spi/issuerservice/credential-revocation-spi/src/main/java/org/eclipse/edc/issuerservice/spi/statuslist/StatusListService.java
spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/VerifiableCredentialResource.java
spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/store/CredentialStore.java

implements a credential revocation service that is based on `BitstringStatusList` credentials. 
There is one general `StatusListService`, that handles common functionality, like parsing the holder credential's status object, and it then delegates implementation-specific actions, like getting or setting bits in the bitstring, down to various `StatusListInfo` objects.
These `StatusListInfo` objects are created through a factory - one per status list type (BitString, StatusList2021,...)
With this, we can support multiple status list implementations at runtime.
_Note: status list implementations that are **not** based on Verifiable Credentials (e.g. a REST service) must implement the `StatusListService` interface!_
to host the revocation credential for public consumption
- the actual hosting …

feat: implement BitstringStatusList revocation service

---

build.gradle.kts
core/identity-hub-core/build.gradle.kts
core/identity-hub-did/build.gradle.kts
core/identity-hub-keypairs/build.gradle.kts
core/identity-hub-participants/build.gradle.kts
core/issuerservice/issuerservice-core/build.gradle.kts
core/issuerservice/issuerservice-credentials/build.gradle.kts
core/issuerservice/issuerservice-participants/build.gradle.kts
core/lib/accesstoken-lib/build.gradle.kts
core/lib/keypair-lib/build.gradle.kts
extensions/api/identity-api/participant-context-api/build.gradle.kts
extensions/api/identity-api/validators/keypair-validators/build.gradle.kts
extensions/api/identity-api/validators/participant-context-validators/build.gradle.kts
extensions/api/identity-api/validators/verifiable-credential-validators/build.gradle.kts
extensions/api/identity-api/verifiable-credentials-api/build.gradle.kts
extensions/api/identityhub-api-authentication/build.gradle.kts
extensions/api/identityhub-api-authorization/build.gradle.kts
extensions/api/issuer-admin-api/attestation-api/build.gradle.kts
extensions/api/issuer-admin-api/credential-definition-api/build.gradle.kts
extensions/api/issuer-admin-api/credentials-api/build.gradle.kts
extensions/api/issuer-admin-api/issuer-admin-api-configuration/build.gradle.kts
extensions/api/issuer-admin-api/participant-api/build.gradle.kts
extensions/did/local-did-publisher/build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts
spi/identity-hub-spi/build.gradle.kts

cleans up the gradle dependencies to avoid unnecessary dependencies
keep the dependency tree clean
- temporarily applied this [dependency analysis](https://github.com/autonomousapps/dependency-analysis-gradle-plugin) dependency-analysis-gradle-plugin
Closes #557

chore: cleanup dependencies

---

extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStoreExtension.java
extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/IssuanceProcessMapping.java
extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/PostgresDialectStatements.java
extensions/store/sql/issuance-process-store-sql/src/test/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStoreTest.java
extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/attestationdefinition/schema/postgres/CredentialDefinitionMapping.java
extensions/store/sql/issuerservice-participant-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/participant/schema/postgres/ParticipantMapping.java

Removes the not needed complexity when querying `credentialDefinitions` by switching to `JsonArrayTranslator`
refactoring

chore: improves issuance process query on credentialDefinitions field

---

core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/IssuanceServicesExtension.java
core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionServiceImpl.java
core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionValidatorRegistryImpl.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionServiceImplTest.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionValidatorRegistryImplTest.java
e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/AttestationApiEndToEndTest.java
e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceApiEndToEndTest.java
extensions/issuance/issuerservice-issuance-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/attestations/IssuanceAttestationsExtension.java
spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/attestation/AttestationDefinitionValidatorRegistry.java

add attestation validation on AttestationDefinitionService
Closes #577 

feat: add attestation validation on AttestationDefinitionService

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestServiceImpl.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestServiceImplTest.java
dist/bom/identityhub-feature-sql-bom/build.gradle.kts

add transactional storing in the CredentialRequestService. Also, the Postgres tests now actually uses PG persistence...

fix: use transactions in credential request

---

core/common-core/src/test/java/org/eclipse/edc/identityhub/defaults/store/InMemoryHolderCredentialRequestStoreTest.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImplTest.java
e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceApiEndToEndTest.java
e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApi.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/model/CredentialRequestDto.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/model/HolderCredentialRequestDto.java
extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/BaseSqlDialectStatements.java
extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/HolderCredentialRequestStoreStatements.java
extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/SqlHolderCredentialRequestStore.java
extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/schema/postgres/HolderCredentialRequestMapping.java
extensions/store/sql/holder-credential-request-store-sql/src/main/resources/holder-credential-request-schema.sql
spi/holder-credential-request-spi/src/main/java/org/eclipse/edc/identityhub/spi/credential/request/model/HolderCredentialRequest.java
spi/holder-credential-request-spi/src/main/java/org/eclipse/edc/identityhub/spi/credential/request/model/HolderRequestState.java
spi/holder-credential-request-spi/src/testFixtures/java/org/eclipse/edc/identityhub/credential/request/test/HolderCredentialRequestStoreTestBase.java
spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/CredentialRequestManager.java

renames `requestId` -> `holderPid` and `issuanceProcessId` -> `issuerPid` to comply with the spec.
spec compliance

refactor: rename requestId and issuanceProcessId

---

docs/developer/decision-records/2025-02-24-sts-deployment-embedded/README.md
docs/developer/decision-records/README.md

adds a decision record about STS always being deployed directly embedded in IdentityHub
simplicity, avoid coupling at database- or HSM-level
- although some connector-related code areas are affected, this is mainly a decision that affects IdentityHub

docs: decision record about STS deployment

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/model/HolderCredentialRequestDto.java
extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiControllerTest.java
extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/SqlHolderCredentialRequestStore.java
spi/verifiable-credential-spi/build.gradle.kts
spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/CredentialRequestManager.java

implement the get-request endpoint to obtain the status of holder credential requests.
Closes #589

feat: add get-request endpoint for holder requests

---

e2e-tests/admin-api-tests/build.gradle.kts
e2e-tests/dcp-issuance-tests/build.gradle.kts
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestStatusApiEndToEndTest.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
protocols/dcp/dcp-issuer/dcp-issuer-api/build.gradle.kts
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/IssuerApiExtension.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApi.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApi.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApiController.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/resources/issuer-api-version.json
protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiControllerTest.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestStatusApiControllerTest.java
protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialRequestStatus.java
protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialRequestStatusTransformer.java
protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialRequestStatusTransformer.java
protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialRequestStatusTransformerTest.java
protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialRequestStatusTransformerTest.java

implements dcp credential request status api
Closes #600 

feat: implements dcp credential request status api

---

README.md
e2e-tests/bom-tests/src/test/java/org/eclipse/edc/test/bom/BomSmokeTests.java
e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubEndToEndTestContext.java
e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubRuntimeConfiguration.java
e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
protocols/dcp/dcp-identityhub/credentials-api-configuration/build.gradle.kts
protocols/dcp/dcp-identityhub/credentials-api-configuration/src/main/java/org/eclipse/edc/identityhub/api/CredentialsApiConfigurationExtension.java
protocols/dcp/dcp-identityhub/credentials-api-configuration/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
protocols/dcp/dcp-identityhub/credentials-api-configuration/src/main/resources/credentials-api-version.json
protocols/dcp/dcp-identityhub/presentation-api/build.gradle.kts
protocols/dcp/dcp-identityhub/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/StorageApiExtension.java
protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/storage/StorageApiController.java
protocols/dcp/dcp-identityhub/storage-api/src/main/resources/storage-api-version.json
protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/storage/StorageApiControllerTest.java
resources/openapi/credentials-api.version
resources/openapi/presentation-api.version
resources/openapi/storage-api.version
settings.gradle.kts
spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/webcontext/IdentityHubApiContext.java

this PR exposes the Storage API and the Credentials API on the same web context called `credentials`.
to that end, the configurations were merged into `web.http.credentials.port/path`, and a dedicated `credentials-api-configuration` was introduced.
Important note: the Storage API is now available under `/v1/.../credentials` instead of `/v1alpha/.../credentials`, because the base URL paths for it and the PResentationAPI _must_ be identical.
the holder DID document only contains one service entry `CredentialService` at which both APIs must be available.
_Please @-mention the …

feat: expose StorageAPI and PresentationAPI on same web context

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialWriterImpl.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialWriterImplTest.java
e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/storage/StorageApiController.java
protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/storage/StorageApiControllerTest.java

this PR adds validation for the credential types and serialization formats of an incoming `CredentialMessage`.
Sending credentials, where the type(s) or serialization formats do not correspond to a previously made `HolderCredentialRequest` is not allowed and will result in a HTTP 403 Unauthorized.
prevent malicious issuers
- this is another thing that the `CredentialWriter` is doing. at some point we might consider splitting it up (which would require another aggregate service), or at least renaming it.
- added some `@DisplayName`s to the Storage API e2e test
Closes #581
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and …

feat: validate incoming CredentialMessage types and formats

---

core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/IssuanceServicesExtension.java
core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionServiceImpl.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionServiceImplTest.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImplTest.java
e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/AttestationApiEndToEndTest.java
e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/HolderApiEndToEndTest.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestStatusApiEndToEndTest.java
extensions/api/issuer-admin-api/attestation-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerAttestationAdminApi.java
extensions/api/issuer-admin-api/attestation-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerAttestationAdminApiController.java
extensions/api/issuer-admin-api/attestation-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerAttestationAdminApiControllerTest.java
extensions/api/issuer-admin-api/holder-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/holder/v1/unstable/IssuerHolderAdminApiControllerTest.java
extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
extensions/store/sql/issuerservice-holder-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/holder/BaseSqlDialectStatements.java
extensions/store/sql/issuerservice-holder-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/holder/HolderStoreStatements.java
extensions/store/sql/issuerservice-holder-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/holder/SqlHolderStore.java
extensions/store/sql/issuerservice-holder-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/holder/schema/postgres/HolderMapping.java
extensions/store/sql/issuerservice-holder-store-sql/src/main/resources/holder-schema.sql
protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiControllerTest.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestStatusApiControllerTest.java
protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpHolderTokenVerifierImplTest.java
spi/issuerservice/issuerservice-holder-spi/src/main/java/org/eclipse/edc/issuerservice/spi/holder/model/Holder.java
spi/issuerservice/issuerservice-holder-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/holder/store/HolderStoreTestBase.java
spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/attestation/AttestationDefinitionService.java

removes attestation linkage to holders
Closes #652 

refactor: removes attestation linkage to holders

---

core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImpl.java
core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGenerator.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImplTest.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGeneratorTest.java
e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceRuntimeConfiguration.java
spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/generator/CredentialGenerator.java
spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/generator/CredentialGeneratorRegistry.java

in addition to generate new credentials, the `CredentialGeneratorRegistry` (and by extension: the `CredentialGenerator`) are now capable of signing existing `VerifiableCredential` objects.
this will be necessary when updating holder credentials, for example after a `credentialStatus` object was added. This happens at a later time, after the credential was generated.
_Please be sure to take a look at the [contributing …

feat: add signing capability to credential generator

---

core/issuerservice/issuerservice-core/build.gradle.kts
core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/CredentialServiceExtension.java
core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java
core/issuerservice/issuerservice-credentials/src/test/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManagerTest.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerExtension.java
extensions/issuance/local-statuslist-publisher/build.gradle.kts
extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalCredentialPublisher.java
extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java
extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/api/StatusListCredentialController.java
extensions/issuance/local-statuslist-publisher/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/issuance/local-statuslist-publisher/src/test/java/org/eclipse/edc/issuerservice/publisher/api/StatusListCredentialControllerTest.java
settings.gradle.kts
spi/did-spi/src/main/java/org/eclipse/edc/identityhub/spi/did/DidDocumentPublisher.java
spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListCredentialPublisher.java
spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListManager.java

This PR adds a web endpoint that exposes status list credentials. It maps to an arbitrary URL path and interprets the last path segment as credential ID.
for example a status list credential with credential ID of `https://foo.com/bar/statuslist/credential-1` would be resolvable under that exact URL.
The endpoint accepts the `Accept` header and attempts to convert. Currently only `application/json` and `application/vc+jwt` are supported, with the latter being the default.
make StatusList credentials publicly available, without authn/authz.
- fixed tests that were failing due to the change in the JTI validation
Closes #550
_Please be sure to take a look at the [contributing …

feat: add StatusList credential endpoint

---

extensions/sts/sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/service/StsClientTokenGeneratorServiceImpl.java
extensions/sts/sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/defaults/StsAccountTokenIssuanceIntegrationTest.java

Currently when generating a token for an `StsAccount` with the `StsClientTokenGeneratorServiceImpl` the `client#clientId` property is used as `participantContextId` passed to the `ParticipantSecureTokenService`. But when creating an `StsAccount` in the `StsAccountServiceImpl` the `clientId` is sourced by the `ParticipantManifest#did`, which means that
The `StsClientTokenGeneratorServiceImpl` works only if the `participantContextId` is equals to the `did` of the participant.
This fixes it by using the `id` instead of  `clientId` of the `StsAccount` 
signature changes, package declarations, bugs that were encountered and were …

fix: use `id` insted of `clientId` when generating the token

---

core/issuerservice/issuerservice-core/build.gradle.kts
core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/CredentialDefinitionLookup.java
core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryCredentialDefinitionStore.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImplTest.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGeneratorTest.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/issuance/credentialdefinition/CredentialDefinitionServiceImplTest.java
core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImplTest.java
e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialDefinitionApiEndToEndTest.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
extensions/api/issuer-admin-api/credential-definition-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentialdefinition/v1/unstable/model/CredentialDefinitionDto.java
extensions/api/issuer-admin-api/credential-definition-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/credentialdefinition/v1/unstable/IssuerCredentialDefinitionAdminApiControllerTest.java
extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/BaseSqlDialectStatements.java
extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/CredentialDefinitionStoreStatements.java
extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/SqlCredentialDefinitionStore.java
extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/schema/postgres/CredentialDefinitionMapping.java
extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/resources/credential-definition-schema.sql
protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImplTest.java
spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/model/CredentialDefinition.java
spi/issuerservice/issuerservice-issuance-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/issuance/credentialdefinition/store/CredentialDefinitionStoreTestBase.java

removes `dataModel` and introduced `formats` in `CredentialDefiniition`. 
This will allow expressing on which format a `CredentialDefiniition` is available and it will bridge with the DCP profile in #676 
Closes #677 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_et …

refactor: removes dataModel in CredentialDefinition

---

core/issuerservice/issuerservice-credentials/build.gradle.kts
core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/CredentialServiceExtension.java
core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/offers/IssuerCredentialOfferServiceImpl.java
core/issuerservice/issuerservice-credentials/src/test/java/org/eclipse/edc/issuerservice/credentials/offers/IssuerCredentialOfferServiceImplTest.java
e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialApiEndToEndTest.java
extensions/api/issuer-admin-api/credentials-api/build.gradle.kts
extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/IssuerCredentialsAdminApiExtension.java

this PR amends a previous development, where Admin API clients can trigger a `CredentialOfferMessage` being sent to the holder.
Previously, that was just an empty JSON object, and now a `CredentialOfferMessage` gets sent.
have API clients send credential offers to holder
Closes #674 …

feat: Issuer sends CredentialOffers

---

dist/bom/identityhub-base-bom/build.gradle.kts
dist/bom/issuerservice-base-bom/build.gradle.kts
protocols/dcp/dcp-core/build.gradle.kts
protocols/dcp/dcp-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/DcpCoreExtension.java
protocols/dcp/dcp-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/DcpProfileRegistryImpl.java
protocols/dcp/dcp-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
protocols/dcp/dcp-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/DcpCoreExtensionTest.java
protocols/dcp/dcp-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/DcpProfileRegistryImplTest.java
protocols/dcp/dcp-issuer/dcp-issuer-core/build.gradle.kts
protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtension.java
protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImpl.java
protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImplTest.java
protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/DcpProfileRegistry.java
protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/DcpProfile.java
settings.gradle.kts

- Introduces a `DcpProfileRegistry` for supporting DCP [profiles](https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/HEAD/#profiles-of-the-decentralized-claims-protocol)
- Bundle by default two profiles defined in DCP spec
- Added profiles check on credential request, `holder -> issuer`, with the input formats.
Currently the profile is not used in the `IssuerMetadata` which will come in #601 
but also in this PR it's not applied when sending the `CredentialOffer`
Closes #676  …

feat: introduce DCP profile

---

protocols/dcp/dcp-identityhub/credential-offer-api/build.gradle.kts
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/CredentialOfferApiExtension.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/ApiSchema.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApi.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApiController.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/validation/CredentialObjectValidator.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/validation/CredentialOfferMessageValidator.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/validation/JsonValidator.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
protocols/dcp/dcp-identityhub/credential-offer-api/src/test/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApiControllerTest.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/test/java/org/eclipse/edc/identityhub/api/validation/CredentialOfferMessageValidatorTest.java
protocols/dcp/dcp-identityhub/credentials-api-configuration/src/main/resources/credentials-api-version.json
protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/DcpConstants.java
protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialOfferMessage.java
protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialOfferMessageTransformer.java
protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialOfferMessageTransformer.java
settings.gradle.kts

this PR adds the holder-side Credential Offer API to receive credential offers from the issuer
notifying holders about available credentials 
- the credential offer is not yet processed. this will come in a subsequent pull-request
Closes #672 

feat: holder-side Credential Offer API

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialStatusCheckServiceImpl.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialStatusCheckServiceImplTest.java
extensions/common/credential-watchdog/src/main/java/org/eclipse/edc/identityhub/common/credentialwatchdog/CredentialWatchdog.java
extensions/common/credential-watchdog/src/main/java/org/eclipse/edc/identityhub/common/credentialwatchdog/CredentialWatchdogExtension.java
extensions/common/credential-watchdog/src/test/java/org/eclipse/edc/identityhub/common/credentialwatchdog/CredentialWatchdogTest.java

this PR enhances the existing `CredentialWatchdog` to also check for credentials that are nearing expiry and kicks off a (re-)issuance request in that case.
slight change to the credential check service: expired credentials can get revoked too, so we need to include them in the check.
Closes #692

feat: implement automatic credential renewal

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGenerator.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGeneratorTest.java

Add an if-statement to check whether the keyId already contains the controller. If not, the publicKeyId is extended by controller + # publicKeyId.
If the controller is already included in the publicKeyId, and a uri is still created together with the controller and publicKeyId, an “invalid Uri” error occurs.
Closes #688 …

fix: prevent 'invalid Uri' error

---

extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java
extensions/issuance/local-statuslist-publisher/src/test/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtensionTest.java

Making sure StatusList API can be exposed to production URL which might not contain any port.
Sometimes API can be exposed behind an API gateway, for example https://apigateway.com/statusList. We are not mentioning any port, the load balancer will do redirection based on the URI path.
Closes #704

fix: Support for custom URL for status list API 

---

extensions/issuance/local-statuslist-publisher/build.gradle.kts
extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java
extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/api/StatusListCredentialController.java
extensions/issuance/local-statuslist-publisher/src/test/java/org/eclipse/edc/issuerservice/publisher/api/StatusListCredentialControllerTest.java

Use mapper including date/time modules in `LocalStatusListCredentialPublisherExtension`.
Fix error during mapping to VC.
@bscholtes1A 
Closes #710 

fix: use mapper embedding date-time in LocalStatusListCredentialPublisherExtension

---

e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialOfferApiEndToEndTest.java
e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/TckTransformer.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/issuance/DcpIssuanceFlowTest.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/issuance/DcpIssuanceFlowTestWithDocker.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/presentation/DcpPresentationFlowTest.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApiController.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/validation/CredentialOfferMessageValidator.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/test/java/org/eclipse/edc/identityhub/api/validation/CredentialOfferMessageValidatorTest.java
protocols/dcp/dcp-identityhub/dcp-identityhub-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpHolderCoreExtension.java
protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/StorageApiExtension.java
protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/storage/StorageApiController.java
protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/validation/CredentialMessageValidator.java
protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/storage/StorageApiControllerTest.java
protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/validation/CredentialMessageValidatorTest.java
protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpCredentialStorageClient.java
protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/DcpConstants.java
protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialMessage.java
protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialMessageTransformer.java
protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialOfferMessageTransformer.java
protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialMessageTransformerTest.java
protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialMessageTransformerTest.java
protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialOfferMessageTransformerTest.java

adds an end-to-end test to assert compliance with the DCP Issuance protocol (including credential offers), targeting the CredentialService.
DCP compliance
- issuance tests targeting the IssuerService will follow in a later iteration
- requires https://github.com/eclipse-dataspacetck/dcp-tck/pull/22

feat: add Credential Issuance tests

---

core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGenerator.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestStatusApiEndToEndTest.java
e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/AbstractIdentityHubExtension.java
e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubExtension.java
e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerExtension.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/issuance/DcpIssuanceFlowTest.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/issuance/DcpIssuanceFlowWithDockerTest.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/issuer/DcpIssuerIssuanceFlowTest.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/issuer/DcpIssuerIssuanceFlowWithDockerTest.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/issuer/DcpIssuerTest.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/presentation/DcpPresentationFlowTest.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/presentation/DcpPresentationFlowWithDockerTest.java
e2e-tests/tck-tests/test-attestations/build.gradle.kts
e2e-tests/tck-tests/test-attestations/src/main/java/org/eclipse/edc/test/e2e/tck/attestation/TckAttestationSource.java
e2e-tests/tck-tests/test-attestations/src/main/java/org/eclipse/edc/test/e2e/tck/attestation/TckAttestationSourceFactory.java
e2e-tests/tck-tests/test-attestations/src/main/java/org/eclipse/edc/test/e2e/tck/attestation/TckAttestationSourceValidator.java
e2e-tests/tck-tests/test-attestations/src/main/java/org/eclipse/edc/test/e2e/tck/attestation/TckTestAttestationsExtension.java
e2e-tests/tck-tests/test-attestations/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiController.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApiController.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiControllerTest.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApiControllerTest.java
protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpCredentialStorageClient.java
protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpHolderTokenVerifierImpl.java
protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtension.java
protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialMessage.java
settings.gradle.kts

adds issuance protocol tests targeting the IssuerService
to achieve compliance with the DCP TCK

feat: add issuance tests for the IssuerService

---

e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/presentation/DcpPresentationFlowTest.java
e2e-tests/tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/presentation/DcpPresentationFlowWithDockerTest.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/resources/issuer-api-version.json

restrict the TCK Test package
do not run verifier tests (they are run in the connector repo)

fix: restrict TCK test package

---

e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpIssuerMetadataApiEndToEndTest.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/IssuerApiExtension.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/issuermetadata/IssuerMetadataApiController.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/issuermetadata/IssuerMetadataApiControllerTest.java

removes the authentication and authorization code from the IssuerMetadata API
it is not required by the DCP Spec and not asserted by the TCK

chore: remove auth from IssuerMetadata API

---

core/common-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java

passes additional params to the revocation services, as needed after upstream change.
upstream change

fix: pass additional properties to revocation service

---

e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
protocols/dcp/dcp-identityhub/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/validation/PresentationQueryValidator.java
protocols/dcp/dcp-identityhub/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredential/PresentationApiController.java
protocols/dcp/dcp-identityhub/presentation-api/src/test/java/org/eclipse/edc/identityservice/api/v1/PresentationApiControllerTest.java
protocols/dcp/dcp-identityhub/presentation-api/src/test/java/org/eclipse/edc/identityservice/api/validation/PresentationQueryValidatorTest.java

prohibits empty `scope` array values in the `PresentationQueryMessage`
recent change in DCP and the TCK
- a HTTP 501 is returned when clients send a `presentationDefinition` instead of HTTP 503

feat: prohibit empty scope array

---

e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java

use a credential validity of 1 year for test credentials
using a credential validity of 1 hour could cause the credential watchdog to consider the credential as "expiring soon", because its grace period is 1 week by default.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contribu …

fix: use longer credential expiry in test

---

e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApi.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiControllerTest.java
extensions/api/issuer-admin-api/attestation-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerAttestationAdminApiControllerTest.java

For credential request API, uses the Location header associated with 201 status code in response instead of string body.
Fix.

fix: fix create credential request response and spec
