eclipse-edc/IdentityHub

docs/developer/decision-records/2022-07-29-self-description/README.md

ADR for Self-Description.
Decision record for adding support of Self-Description in Identity Hub.
https://github.com/agera-edc/MinimumViableDataspace/issues/184

ADR for Self-Description

---

.github/workflows/codeql-analysis.yml
.github/workflows/verify.yaml
CHANGELOG.md
build.gradle.kts
docs/developer/decision-records/2022-08-12-code-quality-tooling/README.md
extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/identityhub/verifier/CredentialsVerifierExtension.java
identity-hub-core/identity-hub-client/src/main/java/org/eclipse/dataspaceconnector/identityhub/client/IdentityHubClient.java

- Run checkstyle on PRs in both upstream and forks.
- Run CodeQL on  PRs in both upstream and forks.
- Fix CodeQL findings
Both Checkstyle and CodeQL are already in use in the EDC framework, so these tools are the natural choice in related projects like the Identity Hub as well.
Closes https://github.com/agera-edc/MinimumViableDataspace/issues/254

CI: Checkstyle and CodeQL

---

.github/workflows/close-inactive-issues.yml
.github/workflows/discord-webhook.yml
.github/workflows/first-interaction.yml
.github/workflows/scan-pull-request.yaml

Enables GitHub notifications for new issues, discussions and PRs. 
Update pr check action. Add first interaction and stale bot
Optimize working with GitHub.
Secret for this repo has already been set.

feat(workflows): add discord webhook for issues, discussions and pull requests

---

extensions/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/IdentityHubApiConfiguration.java
resources/checkstyle-config.xml

Add strict checks on file header format
Headers consistency
Closes #68

feat(build): add strict checkstyle on file header #61 

---

extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStore.java

Adapts the code to fit to the latest changes in the upstream:
- update usage of the `CosmosDbApi`
fix compiler errors
.
.

chore: adapt code base to comply with current edc upstream main

---

build.gradle.kts
gradle.properties
settings.gradle.kts

fix: cleanup version to fix release

---

.github/ISSUE_TEMPLATE/feature_request.md
build.gradle.kts
core/identity-hub-client/build.gradle.kts
core/identity-hub-credentials-verifier/build.gradle.kts
core/identity-hub/build.gradle.kts
extensions/credentials/identity-hub-credentials-jwt/build.gradle.kts
extensions/identity-hub-api/build.gradle.kts
extensions/identity-hub-verifier-jwt/build.gradle.kts
extensions/self-description-api/build.gradle.kts
extensions/store/cosmos/identity-hub-store-cosmos/build.gradle.kts
extensions/store/sql/identity-hub-store-sql/build.gradle.kts
gradle/libs.versions.toml
identity-hub-cli/build.gradle.kts
launcher/build.gradle.kts
settings.gradle.kts
spi/identity-hub-client-spi/build.gradle.kts
spi/identity-hub-spi/build.gradle.kts
spi/identity-hub-store-spi/build.gradle.kts
system-tests/build.gradle.kts

Publishes version catalog
Closes #94

feat: publish version catalog

---

core/identity-hub-client/build.gradle.kts
core/identity-hub-credentials-verifier/build.gradle.kts
core/identity-hub-credentials-verifier/src/main/java/org/eclipse/edc/identityhub/verifier/AggregatedResult.java
extensions/credentials/identity-hub-credentials-jwt/build.gradle.kts
extensions/identity-hub-verifier-jwt/build.gradle.kts
system-tests/build.gradle.kts

Fix compilation issue caused by api change in `AbstractResult` class.
- cleaned up some unneeded dependencies

fix: compilation issue

---

core/identity-hub-credentials-verifier/build.gradle.kts
core/identity-hub/build.gradle.kts
extensions/credentials/identity-hub-credentials-jwt/build.gradle.kts
extensions/identity-hub-api/build.gradle.kts
extensions/identity-hub-verifier-jwt/build.gradle.kts
extensions/self-description-api/build.gradle.kts
extensions/store/cosmos/identity-hub-store-cosmos/build.gradle.kts
extensions/store/sql/identity-hub-store-sql/build.gradle.kts
gradle/libs.versions.toml
identity-hub-cli/build.gradle.kts
settings.gradle.kts
spi/identity-hub-client-spi/build.gradle.kts
spi/identity-hub-spi/build.gradle.kts
spi/identity-hub-store-spi/build.gradle.kts
system-tests/build.gradle.kts

build(deps): remove root version catalog dependency

---

gradle.properties

BugFix metamodelversion in gradle.properties file.
BugFix
Closes #109

fix: metaModelVersion -Snapshot to 0.1.3-SNAPSHOT

---

.github/workflows/dependency-check.yml
DEPENDENCIES

Update `DEPENDENCIES` file
Fix build.

fix: update `DEPENDENCIES` file

---

.github/release.yaml

build: update release.yaml

---

DEPENDENCIES
docs/developer/decision-records/2023-09-27-adoption_of_the_identity_and_trust_protocol/README.md

adds a decision record about the adoption of the Identity And Trust Protocols (IATP)
transparent decisions

docs: add decision record about the adoption of IATP

---

DEPENDENCIES
core/identity-hub-api/src/test/java/org/eclipse/edc/identityservice/api/v1/PresentationApiControllerTest.java
core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/PresentationGeneratorImpl.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ResolutionApiComponentTest.java

fixes a compile error after upstream changes
compile errors

fix: compile errors

---

DEPENDENCIES
extensions/store/sql/identity-hub-did-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension

Fix the provider of `SqlCredentialStore`.
Bug.

fix: fix `SqlCredentialStore` provider

---

docs/developer/architecture/mgmt-api.security.md

Adds documentation about Authentication, Authorization and RBAC to the docs folder.
documentation

docs: add docs about API security

---

.github/workflows/publish-openapi-ui.yml
.github/workflows/release-identityhub.yml
DEPENDENCIES

Add workflow to publish openapi UI.
API documentation

docs: publish openapi ui

---

DEPENDENCIES
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java

fix: udpate package import for transformer

---

DEPENDENCIES
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApiController.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/token/verification/AccessTokenVerifierImpl.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/token/verification/AccessTokenVerifierImplComponentTest.java
core/identity-hub-credentials/src/test/java/org/eclipse/edc/identityhub/token/verification/AccessTokenVerifierImplTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiComponentTest.java
spi/identity-hub-spi/src/testFixtures/java/org/eclipse/edc/identityhub/junit/testfixtures/JwtCreationUtil.java

incorporate  the latest IATP changes specifically mv `access_token` `token`
iatp compliance

chore: updates with the latest IATP changes

---

core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/defaults/CredentialResourceLookup.java
extensions/store/sql/identity-hub-credentials-store-sql/build.gradle.kts
extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/schema/postgres/CredentialJsonMapping.java

Updates the package import for `PathItem`
it was recently refactored upstream

fix: update import pathitem

---

e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubRuntimeConfiguration.java

fix: compile errors PARTICIPANT_ID

---

DEPENDENCIES
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubRuntimeConfiguration.java
extensions/api/participant-context-mgmt-api/build.gradle.kts
extensions/store/sql/identity-hub-credentials-store-sql/docs/schema.sql
extensions/store/sql/identity-hub-keypair-store-sql/docs/schema.sql
extensions/store/sql/identity-hub-participantcontext-store-sql/docs/schema.sql
gradle/libs.versions.toml

Add missing `IF NOT EXIST` statements in SQL stores.
Align with other stores.

fix: add missing `IF NOT EXIST` statements in SQL stores

---

DEPENDENCIES
gradle/libs.versions.toml

build: fix dependency

---

DEPENDENCIES
gradle/libs.versions.toml

build: fix dependencies

---

.github/workflows/publish-autodoc.yml
.github/workflows/release-identityhub.yml
DEPENDENCIES

Add/fix worfklows for autodoc and openapi publication.
Autodoc and openapi publication

docs: workflows for openapi and autodoc publication

---

DEPENDENCIES
build.gradle.kts
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
core/identity-hub-credentials/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java

Adapts to upstream refactoring after module/package restructure

fix: compile errors after EDC refactor

---

extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/schema/postgres/CredentialJsonMapping.java

fix javadoc error
javadoc task fails

chore: fix javadoc error

---

DEPENDENCIES
core/identity-hub-api/build.gradle.kts
core/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
gradle/libs.versions.toml

fix(dep): update the transform dependency

---

DEPENDENCIES
core/identity-hub-credentials/build.gradle.kts
extensions/api/identityhub-management-api-validators/build.gradle.kts
extensions/api/keypair-mgmt-api/build.gradle.kts
extensions/api/participant-context-mgmt-api/build.gradle.kts
extensions/api/verifiable-credential-mgmt-api/build.gradle.kts
extensions/common/security/build.gradle.kts
extensions/store/sql/identity-hub-credentials-store-sql/build.gradle.kts
gradle/libs.versions.toml

fix(dependency): update more dependencies

---

DEPENDENCIES
core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java

fix: use keyId in DID Documents

---

docs/developer/decision-records/2024-09-02-resource-operations/README.md
docs/developer/decision-records/README.md

Outlined resource operation consistency. See the linked issue.
Closes #440

docs: Add resource operations Decision Record

---

e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java

aligns the `updateParticipantContext` action (activate and deactivate) with the decision record. Code was already aligned, added some tests.
compliance with D-R

chore: align updateParticipantContext with DR

---

core/presentation-api/build.gradle.kts
e2e-tests/api-tests/build.gradle.kts
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndExtension.java
extensions/api/identity-api/api-configuration/build.gradle.kts
extensions/api/identity-api/did-api/build.gradle.kts
extensions/api/identity-api/participant-context-api/build.gradle.kts
extensions/api/identityhub-api-authentication/build.gradle.kts
extensions/api/identityhub-api-authorization/build.gradle.kts
extensions/store/sql/identity-hub-credentials-store-sql/build.gradle.kts
extensions/store/sql/identity-hub-did-store-sql/build.gradle.kts
extensions/store/sql/identity-hub-keypair-store-sql/build.gradle.kts
extensions/store/sql/identity-hub-participantcontext-store-sql/build.gradle.kts
gradle/libs.versions.toml

build: fix compilation

---

README.md

docs: fixed an incorrect port

---

.github/workflows/verify.yaml
e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubRuntimeConfiguration.java
e2e-tests/bom-tests/src/test/java/org/eclipse/edc/test/bom/BomSmokeTests.java
e2e-tests/sts-tests/src/test/java/org/eclipse/edc/identityhub/tests/sts/accountservice/RemoteAccountServiceIntegrationTest.java

fix: compilation

---

docs/developer/architecture/issuer/issuance/issuance.process.md

Adds the architecture document for the issuance process in the Issuer Service.

docs: Add issuance process architecture document

---

docs/developer/architecture/issuer/credential-revocation/credential-revocation.md
extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerCredentialsAdminApiController.java
resources/openapi/presentation-api.version

documents the status list mechanism
does documentation really need justification?

docs: documentation about the status list credential mechanism

---

protocols/dcp/dcp-identityhub/storage-api/build.gradle.kts
settings.gradle.kts

Closes https://github.com/eclipse-edc/MinimumViableDataspace/issues/430

fix: remove unneeded module

---

core/common-core/src/main/java/org/eclipse/edc/identityhub/defaults/store/InMemoryHolderCredentialRequestStore.java
core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryIssuanceProcessStore.java
extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/schema/postgres/HolderCredentialRequestMapping.java
extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/IssuanceProcessMapping.java
spi/holder-credential-request-spi/src/testFixtures/java/org/eclipse/edc/identityhub/credential/request/test/HolderCredentialRequestStoreTestBase.java
spi/issuerservice/issuerservice-issuance-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/issuance/process/store/IssuanceProcessStoreTestBase.java

fix after upstream changes on state filtering
Ref https://github.com/eclipse-edc/Connector/pull/4829

chore: fix after upstream changes on state filtering

---

core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImplTest.java

No need to poll for holder credential requests that are in state `REQUESTED` because the Issuer should have an async way to send rejection messages.
c.f. https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol/issues/182
reduce complexity
should an async rejection message be missed, and thus the state get out of sync, the credential request needs to be reconciled and potentially re-requested manually. 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette. …

docs: remove polling requests that are in REQUESTED

---

e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestStatusApiEndToEndTest.java
e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceEndToEndTestContext.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApi.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiController.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApi.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApiController.java
protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/resources/issuer-api-version.json
protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiControllerTest.java

change dcp issuance base path
consistency
Closes #633 

feat: change dcp issuance base path

---

core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/mapping/IssuanceClaimsMapperImplTest.java
spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/mapping/IssuanceClaimsMapper.java

fixes the `IssuanceClaimsMapper`, so that output claims are collated, and the input claims are always passed into the `apply` function

fix: issuance claims mapper

---

extensions/sts/sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/EmbeddedStsServiceExtension.java
extensions/sts/sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/service/EmbeddedSecureTokenService.java
extensions/sts/sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/defaults/StsAccountTokenIssuanceIntegrationTest.java
extensions/sts/sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/service/EmbeddedSecureTokenServiceTest.java

Closes https://github.com/eclipse-edc/Connector/issues/4836

feat: switch JTI validation to black-listing

---

core/common-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialApiEndToEndTest.java
e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialOfferApiEndToEndTest.java
extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/api/identity-api/did-api/src/main/java/org/eclipse/edc/identityhub/api/didmanagement/v1/unstable/DidManagementApi.java
extensions/api/identity-api/keypair-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/unstable/KeyPairResourceApi.java
extensions/api/identity-api/participant-context-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredential/v1/unstable/ParticipantContextApi.java
extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApi.java
extensions/api/issuer-admin-api/credential-definition-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentialdefinition/v1/unstable/IssuerCredentialDefinitionAdminApi.java
extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerCredentialsAdminApi.java
extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerCredentialsAdminApiController.java
extensions/api/issuer-admin-api/credentials-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerCredentialsAdminApiControllerTest.java
extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApi.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApiController.java
protocols/dcp/dcp-identityhub/credential-offer-api/src/test/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApiControllerTest.java
protocols/dcp/dcp-identityhub/credentials-api-configuration/src/main/resources/credentials-api-version.json

Use status code 204 in swagger spec for APIs that does not return anything.
Fix.
Closes #731 

fix: correct usage of status code 200 in swagger spec

---

build.gradle.kts
gradle/libs.versions.toml

related to https://github.com/eclipse-edc/GradlePlugins/pull/354

build: use edc-build from Gradle Plugin Portal

---

extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
extensions/api/identity-api/participant-context-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredential/v1/unstable/ParticipantContextApi.java

Fix API docs, remove `@Content` where a 204 is expected
fix api docs

docs: fix openapi docs
